#!/usr/bin/env python3
"""
Migration: Intraday Leverage Table

Creates the intraday_leverage table storing per-symbol intraday leverage
multipliers for NSE stocks. Seeds 1579 rows from broker margin data.

init_db() in the main database module does not cover this table, so this
script is what reaches deployments that upgrade with `git pull`.

This migration is idempotent - safe to run multiple times.

Usage:
    cd upgrade
    uv run migrate_intraday_leverage.py           # Apply migration
    uv run migrate_intraday_leverage.py --status  # Check status without changing anything
"""

import argparse
import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Add parent directory to path for imports
sys.path.insert(0, PROJECT_ROOT)
# Register the app's SQLite pragmas on this process's engines, so a migration
# waits the same 15s for a write lock the running app does instead of the
# sqlite3 default of 5s (GitHub issue #1726).
import _pragmas  # noqa: F401,E402
from sqlalchemy import create_engine, inspect, text
from sqlalchemy.pool import NullPool

TABLE_NAME = "intraday_leverage"


def resolve_sqlite_path(db_url):
    """Make a relative sqlite:/// path absolute against the project root.

    The documented invocation is `cd upgrade && uv run migrate_intraday_leverage.py`,
    and DATABASE_URL is relative by default ("sqlite:///db/openalgo.db"). Left
    relative it resolves against the current directory, so running from
    upgrade/ would point at upgrade/db/openalgo.db - which SQLAlchemy creates
    empty on connect. The migration would then report success having created
    its tables in a database the app never opens.
    """
    prefix = "sqlite:///"
    if not db_url.startswith(prefix):
        return db_url
    path = db_url[len(prefix) :]
    if not path or path == ":memory:" or os.path.isabs(path):
        return db_url
    return prefix + os.path.join(PROJECT_ROOT, path)


def get_database_url():
    """Get database URL from environment"""
    from dotenv import load_dotenv

    load_dotenv()
    return resolve_sqlite_path(os.getenv("DATABASE_URL", "sqlite:///db/openalgo.db"))


def table_exists(engine, table_name):
    """Check if a table exists in the database"""
    return table_name in inspect(engine).get_table_names()


def get_row_count(engine, table_name):
    """Get the row count of a table"""
    with engine.connect() as conn:
        return conn.execute(text(f"SELECT COUNT(*) FROM {table_name}")).scalar()


def create_table(engine):
    """Create the intraday_leverage table."""
    if table_exists(engine, TABLE_NAME):
        print(f"  [SKIP] {TABLE_NAME} table already exists")
        return True

    print(f"  [CREATE] Creating {TABLE_NAME} table...")

    sql = text("""
        CREATE TABLE intraday_leverage (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            symbol TEXT NOT NULL,
            exchange TEXT NOT NULL DEFAULT 'NSE',
            multiplier REAL NOT NULL,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(symbol, exchange)
        )
    """)

    with engine.connect() as conn:
        conn.execute(sql)
        conn.commit()

    print(f"  [OK] {TABLE_NAME} table created")
    return True


def seed_data(engine):
    """Seed the table with NSE stock leverage multipliers."""
    count = get_row_count(engine, TABLE_NAME)
    if count > 0:
        print(f"  [SKIP] {TABLE_NAME} already has {count} rows")
        return True

    print("  [SEED] Inserting NSE leverage multipliers...")

    insert_statements = _get_seed_sql()

    with engine.connect() as conn:
        for stmt in insert_statements:
            conn.execute(text(stmt))
        conn.commit()

    count = get_row_count(engine, TABLE_NAME)
    print(f"  [OK] Seeded {count} rows into {TABLE_NAME}")
    return True


def _get_seed_sql():
    """Return list of batched INSERT statements for seed data."""
    return [
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('20MICRONS', 'NSE', 4),
('360ONE', 'NSE', 5),
('3BBLACKBIO', 'NSE', 4),
('3MINDIA', 'NSE', 5),
('5PAISA', 'NSE', 4),
('63MOONS', 'NSE', 5),
('AADHARHFC', 'NSE', 5),
('AARON', 'NSE', 1),
('AARTIDRUGS', 'NSE', 5),
('AARTIIND', 'NSE', 5),
('AARTIPHARM', 'NSE', 5),
('AASTHA', 'NSE', 4),
('AAVAS', 'NSE', 4),
('ABB', 'NSE', 5),
('ABBOTINDIA', 'NSE', 5),
('ABCAPITAL', 'NSE', 5),
('ABDL', 'NSE', 5),
('ABFRL', 'NSE', 5),
('ABLBL', 'NSE', 5),
('ABREL', 'NSE', 5),
('ABSLAMC', 'NSE', 5),
('ACC', 'NSE', 5),
('ACCELYA', 'NSE', 4),
('ACE', 'NSE', 5),
('ACI', 'NSE', 5),
('ACMESOLAR', 'NSE', 5),
('ACUTAAS', 'NSE', 5),
('ADANIENSOL', 'NSE', 5),
('ADANIENT', 'NSE', 5),
('ADANIGREEN', 'NSE', 5),
('ADANIPORTS', 'NSE', 5),
('ADANIPOWER', 'NSE', 5),
('ADFFOODS', 'NSE', 5),
('ADOR', 'NSE', 5),
('ADSL', 'NSE', 1),
('ADVAIT', 'NSE', 5),
('ADVANCE', 'NSE', 5),
('ADVENTHTL', 'NSE', 1),
('ADVENZYMES', 'NSE', 5),
('AEGISLOG', 'NSE', 5),
('AEGISVOPAK', 'NSE', 5),
('AEQUS', 'NSE', 5),
('AEROENTER', 'NSE', 4),
('AEROFLEX', 'NSE', 5),
('AETHER', 'NSE', 5),
('AFCONS', 'NSE', 5),
('AFFLE', 'NSE', 5),
('AGARIND', 'NSE', 5),
('AGARWALEYE', 'NSE', 4),
('AGI', 'NSE', 5),
('AGIIL', 'NSE', 5),
('AGL', 'NSE', 2),
('AHCL', 'NSE', 5),
('AHLUCONT', 'NSE', 4),
('AIAENG', 'NSE', 5),
('AIIL', 'NSE', 5),
('AJANTPHARM', 'NSE', 5),
('AJAXENGG', 'NSE', 4),
('AJMERA', 'NSE', 4),
('AKCAPIT', 'NSE', 4),
('AKUMS', 'NSE', 5),
('ALEMBICLTD', 'NSE', 4),
('ALGOQUANT', 'NSE', 4),
('ALICON', 'NSE', 4),
('ALIVUS', 'NSE', 5),
('ALKEM', 'NSE', 5),
('ALKYLAMINE', 'NSE', 5),
('ALLCARGO', 'NSE', 4),
('ALLDIGI', 'NSE', 4),
('ALLTIME', 'NSE', 4),
('ALMONDZ', 'NSE', 1),
('ALOKINDS', 'NSE', 4),
('ALPHA', 'NSE', 1),
('ALPINETEX', 'NSE', 1),
('ALPL30IETF', 'NSE', 1),
('AMAGI', 'NSE', 5),
('AMBER', 'NSE', 5),
('AMBUJACEM', 'NSE', 5),
('AMNPLST', 'NSE', 1),
('AMRUTANJAN', 'NSE', 4),
('ANANDRATHI', 'NSE', 5),
('ANANTRAJ', 'NSE', 5),
('ANDHRAPAP', 'NSE', 4),
('ANDHRSUGAR', 'NSE', 4),
('ANDREWYU', 'NSE', 4),
('ANGELONE', 'NSE', 5),
('ANTELOPUS', 'NSE', 4),
('ANTHEM', 'NSE', 5),
('ANUP', 'NSE', 4),
('ANURAS', 'NSE', 5),
('APARINDS', 'NSE', 5),
('APCOTEXIND', 'NSE', 5),
('APEX', 'NSE', 4),
('APLAPOLLO', 'NSE', 5),
('APLLTD', 'NSE', 5),
('APOLLO', 'NSE', 5),
('APOLLOHOSP', 'NSE', 5),
('APOLLOPIPE', 'NSE', 5),
('APOLLOTYRE', 'NSE', 5),
('APTUS', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('ARE&M', 'NSE', 5),
('ARFIN', 'NSE', 5),
('ARIHANT', 'NSE', 4),
('ARIHANTCAP', 'NSE', 1),
('ARIS', 'NSE', 5),
('ARKADE', 'NSE', 5),
('ARMANFIN', 'NSE', 5),
('ARSSBL', 'NSE', 4),
('ARTEMISMED', 'NSE', 5),
('ARVIND', 'NSE', 5),
('ARVINDFASN', 'NSE', 5),
('ARVSMART', 'NSE', 1),
('ASAHIINDIA', 'NSE', 5),
('ASAL', 'NSE', 1),
('ASALCBR', 'NSE', 4),
('ASHAPURMIN', 'NSE', 5),
('ASHIANA', 'NSE', 4),
('ASHOKA', 'NSE', 5),
('ASHOKLEY', 'NSE', 5),
('ASIANENE', 'NSE', 5),
('ASIANPAINT', 'NSE', 5),
('ASIANTILES', 'NSE', 5),
('ASKAUTOLTD', 'NSE', 5),
('ASTEC', 'NSE', 4),
('ASTERDM', 'NSE', 5),
('ASTRAL', 'NSE', 5),
('ASTRAMICRO', 'NSE', 5),
('ASTRAZEN', 'NSE', 5),
('ATALREAL', 'NSE', 5),
('ATGL', 'NSE', 5),
('ATHERENERG', 'NSE', 5),
('ATUL', 'NSE', 5),
('ATULAUTO', 'NSE', 5),
('AUBANK', 'NSE', 5),
('AURIONPRO', 'NSE', 5),
('AUROPHARMA', 'NSE', 5),
('AURUM', 'NSE', 4),
('AUTOAXLES', 'NSE', 4),
('AUTOBEES', 'NSE', 5),
('AUTOIETF', 'NSE', 1),
('AVADHSUGAR', 'NSE', 4),
('AVALON', 'NSE', 5),
('AVANTEL', 'NSE', 5),
('AVANTIFEED', 'NSE', 5),
('AVL', 'NSE', 5),
('AWFIS', 'NSE', 4),
('AWHCL', 'NSE', 4),
('AWL', 'NSE', 5),
('AXISBANK', 'NSE', 5),
('AXISCADES', 'NSE', 4),
('AYE', 'NSE', 5),
('AYMSYNTEX', 'NSE', 1),
('AZAD', 'NSE', 5),
('BAJAJ', 'NSE', 5),
('BAJAJCON', 'NSE', 5),
('BAJAJELEC', 'NSE', 4),
('BAJAJFINSV', 'NSE', 5),
('BAJAJHCARE', 'NSE', 4),
('BAJAJHFL', 'NSE', 5),
('BAJAJHIND', 'NSE', 5),
('BAJAJHLDNG', 'NSE', 5),
('BAJAJST', 'NSE', 1),
('BAJEL', 'NSE', 4),
('BAJFINANCE', 'NSE', 5),
('BALAJITELE', 'NSE', 1),
('BALAMINES', 'NSE', 5),
('BALKRISIND', 'NSE', 5),
('BALMLAWRIE', 'NSE', 4),
('BALRAMCHIN', 'NSE', 5),
('BALUFORGE', 'NSE', 5),
('BANCOINDIA', 'NSE', 5),
('BANDHANBNK', 'NSE', 5),
('BANKBARODA', 'NSE', 5),
('BANKBEES', 'NSE', 5),
('BANKBETA', 'NSE', 1),
('BANKIETF', 'NSE', 1),
('BANKINDIA', 'NSE', 5),
('BANKNIFTY1', 'NSE', 1),
('BANSALWIRE', 'NSE', 4),
('BASF', 'NSE', 4),
('BATAINDIA', 'NSE', 5),
('BAYERCROP', 'NSE', 5),
('BBL', 'NSE', 5),
('BBOX', 'NSE', 5),
('BBTC', 'NSE', 4),
('BCG', 'NSE', 4),
('BCLIND', 'NSE', 4),
('BDL', 'NSE', 5),
('BECTORFOOD', 'NSE', 5),
('BEL', 'NSE', 5),
('BELRISE', 'NSE', 5),
('BEML', 'NSE', 5),
('BENARAS', 'NSE', 1),
('BEPL', 'NSE', 5),
('BERGEPAINT', 'NSE', 5),
('BESTAGRO', 'NSE', 5),
('BETA', 'NSE', 5),
('BFINVEST', 'NSE', 4),
('BFUTILITIE', 'NSE', 4),
('BHAGCHEM', 'NSE', 4);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('BHARATCOAL', 'NSE', 5),
('BHARATFORG', 'NSE', 5),
('BHARATRAS', 'NSE', 1),
('BHARATSE', 'NSE', 4),
('BHARATWIRE', 'NSE', 4),
('BHARTIARTL', 'NSE', 5),
('BHARTIHEXA', 'NSE', 5),
('BHEL', 'NSE', 5),
('BIKAJI', 'NSE', 4),
('BIOCON', 'NSE', 5),
('BIRET', 'NSE', 4),
('BIRLACORPN', 'NSE', 5),
('BIRLANU', 'NSE', 4),
('BLACKBUCK', 'NSE', 5),
('BLKASHYAP', 'NSE', 4),
('BLS', 'NSE', 5),
('BLSE', 'NSE', 5),
('BLUECLOUDS', 'NSE', 4),
('BLUEDART', 'NSE', 5),
('BLUEJET', 'NSE', 5),
('BLUESTARCO', 'NSE', 5),
('BLUESTONE', 'NSE', 5),
('BLUSPRING', 'NSE', 4),
('BOMDYEING', 'NSE', 4),
('BOROLTD', 'NSE', 4),
('BORORENEW', 'NSE', 5),
('BOROSCI', 'NSE', 4),
('BOSCH', 'NSE', 5),
('BOSCHLTD', 'NSE', 5),
('BPCL', 'NSE', 5),
('BRIGADE', 'NSE', 5),
('BRIGHOTEL', 'NSE', 1),
('BRITANNIA', 'NSE', 5),
('BSE', 'NSE', 5),
('BSLGOLDETF', 'NSE', 1),
('BSLNIFTY', 'NSE', 1),
('BSOFT', 'NSE', 5),
('BUILDPRO', 'NSE', 5),
('BUTTERFLY', 'NSE', 4),
('CAMLINFINE', 'NSE', 5),
('CAMPUS', 'NSE', 5),
('CAMS', 'NSE', 5),
('CANBK', 'NSE', 5),
('CANFINHOME', 'NSE', 5),
('CANHLIFE', 'NSE', 5),
('CANTABIL', 'NSE', 4),
('CAPACITE', 'NSE', 4),
('CAPILLARY', 'NSE', 5),
('CAPINVIT', 'NSE', 1),
('CAPITALSFB', 'NSE', 4),
('CAPLIPOINT', 'NSE', 5),
('CARBORUNIV', 'NSE', 5),
('CARERATING', 'NSE', 5),
('CARRARO', 'NSE', 4),
('CARTRADE', 'NSE', 5),
('CARYSIL', 'NSE', 5),
('CASTROLIND', 'NSE', 5),
('CCAVENUE', 'NSE', 5),
('CCL', 'NSE', 5),
('CDSL', 'NSE', 5),
('CEATLTD', 'NSE', 5),
('CEIGALL', 'NSE', 5),
('CEINSYS', 'NSE', 4),
('CELLO', 'NSE', 4),
('CENTENKA', 'NSE', 5),
('CENTRALBK', 'NSE', 5),
('CENTRUM', 'NSE', 4),
('CENTUM', 'NSE', 5),
('CENTURYPLY', 'NSE', 5),
('CERA', 'NSE', 5),
('CESC', 'NSE', 5),
('CEWATER', 'NSE', 1),
('CGCL', 'NSE', 5),
('CGPOWER', 'NSE', 5),
('CHALET', 'NSE', 5),
('CHAMBLFERT', 'NSE', 5),
('CHEMPLASTS', 'NSE', 5),
('CHENNPETRO', 'NSE', 5),
('CHOICEIN', 'NSE', 5),
('CHOLAFIN', 'NSE', 5),
('CHOLAHLDNG', 'NSE', 5),
('CIEINDIA', 'NSE', 5),
('CIPLA', 'NSE', 5),
('CLEAN', 'NSE', 5),
('CLEANMAX', 'NSE', 5),
('CLSEL', 'NSE', 4),
('CMLL', 'NSE', 5),
('CMPDI', 'NSE', 5),
('CMRGREEN', 'NSE', 5),
('CMSINFO', 'NSE', 5),
('CNL', 'NSE', 5),
('COALINDIA', 'NSE', 5),
('COCHINSHIP', 'NSE', 5),
('COCKERILL', 'NSE', 4),
('COFORGE', 'NSE', 5),
('COHANCE', 'NSE', 5),
('COLPAL', 'NSE', 5),
('COMSYN', 'NSE', 5),
('CONCOR', 'NSE', 5),
('CONCORDBIO', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('CONFIPET', 'NSE', 5),
('CONSUMBEES', 'NSE', 1),
('CONSUMER', 'NSE', 1),
('CONSUMIETF', 'NSE', 1),
('CONTROLPR', 'NSE', 1),
('COROMANDEL', 'NSE', 5),
('CORONA', 'NSE', 5),
('COSMOFIRST', 'NSE', 5),
('CPEDU', 'NSE', 1),
('CPSEETF', 'NSE', 4),
('CRAFTSMAN', 'NSE', 5),
('CRAMC', 'NSE', 5),
('CREDITACC', 'NSE', 5),
('CRISIL', 'NSE', 5),
('CRIZAC', 'NSE', 5),
('CROMPTON', 'NSE', 5),
('CSBBANK', 'NSE', 5),
('CSM', 'NSE', 4),
('CUB', 'NSE', 5),
('CUBEINVIT', 'NSE', 5),
('CUMMINSIND', 'NSE', 5),
('CUPID', 'NSE', 5),
('CYIENT', 'NSE', 5),
('CYIENTDLM', 'NSE', 5),
('DABUR', 'NSE', 5),
('DALBHARAT', 'NSE', 5),
('DALMIASUG', 'NSE', 4),
('DAMCAPITAL', 'NSE', 4),
('DATAMATICS', 'NSE', 5),
('DATAPATTNS', 'NSE', 5),
('DBCORP', 'NSE', 4),
('DBL', 'NSE', 5),
('DCAL', 'NSE', 4),
('DCBBANK', 'NSE', 5),
('DCI', 'NSE', 1),
('DCMSHRIRAM', 'NSE', 5),
('DCW', 'NSE', 4),
('DCXINDIA', 'NSE', 5),
('DDEVPLSTIK', 'NSE', 4),
('DECNGOLD', 'NSE', 5),
('DEEPAKFERT', 'NSE', 5),
('DEEPAKNTR', 'NSE', 5),
('DEEPINDS', 'NSE', 5),
('DEFENCE', 'NSE', 1),
('DELHIVERY', 'NSE', 5),
('DELTACORP', 'NSE', 4),
('DEN', 'NSE', 1),
('DENORA', 'NSE', 1),
('DENTA', 'NSE', 5),
('DEVYANI', 'NSE', 5),
('DHAMPURSUG', 'NSE', 1),
('DHANBANK', 'NSE', 5),
('DHANUKA', 'NSE', 5),
('DIAMONDYD', 'NSE', 4),
('DIFFNKG', 'NSE', 4),
('DIGITIDE', 'NSE', 4),
('DISAQ', 'NSE', 1),
('DIVGIITTS', 'NSE', 4),
('DIVISLAB', 'NSE', 5),
('DIXON', 'NSE', 5),
('DJML', 'NSE', 4),
('DLF', 'NSE', 5),
('DLINKINDIA', 'NSE', 4),
('DMART', 'NSE', 5),
('DMCC', 'NSE', 1),
('DODLA', 'NSE', 5),
('DOLLAR', 'NSE', 4),
('DOMS', 'NSE', 5),
('DPABHUSHAN', 'NSE', 5),
('DREDGECORP', 'NSE', 5),
('DRREDDY', 'NSE', 5),
('DWARKESH', 'NSE', 4),
('DYCL', 'NSE', 5),
('DYNAMATECH', 'NSE', 5),
('EASEMYTRIP', 'NSE', 5),
('EBBETF0430', 'NSE', 1),
('EBGNG', 'NSE', 4),
('ECLERX', 'NSE', 5),
('EDELWEISS', 'NSE', 5),
('EFCIL', 'NSE', 5),
('EGOLD', 'NSE', 1),
('EICHERMOT', 'NSE', 5),
('EIDPARRY', 'NSE', 5),
('EIEL', 'NSE', 5),
('EIHAHOTELS', 'NSE', 1),
('EIHOTEL', 'NSE', 5),
('EIMCOELECO', 'NSE', 4),
('EKC', 'NSE', 4),
('ELANTAS', 'NSE', 1),
('ELECON', 'NSE', 5),
('ELECTCAST', 'NSE', 4),
('ELGIEQUIP', 'NSE', 5),
('ELLEN', 'NSE', 4),
('ELPROINTL', 'NSE', 4),
('EMAMILTD', 'NSE', 5),
('EMBASSY', 'NSE', 5),
('EMBDL', 'NSE', 5),
('EMCURE', 'NSE', 5),
('EMIL', 'NSE', 5),
('EMKAY', 'NSE', 1);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('EMMVEE', 'NSE', 5),
('EMSLIMITED', 'NSE', 4),
('EMUDHRA', 'NSE', 5),
('ENDURANCE', 'NSE', 5),
('ENERGY', 'NSE', 1),
('ENGINERSIN', 'NSE', 5),
('ENRIN', 'NSE', 5),
('ENTERO', 'NSE', 5),
('EPACK', 'NSE', 5),
('EPACKPEB', 'NSE', 5),
('EPIGRAL', 'NSE', 5),
('EPL', 'NSE', 5),
('EQUITASBNK', 'NSE', 5),
('ERIS', 'NSE', 5),
('ESABINDIA', 'NSE', 4),
('ESCORTS', 'NSE', 5),
('ESILVER', 'NSE', 1),
('ETERNAL', 'NSE', 5),
('ETHOSLTD', 'NSE', 4),
('EUREKAFORB', 'NSE', 5),
('EUROPRATIK', 'NSE', 5),
('EVEREADY', 'NSE', 4),
('EVINDIA', 'NSE', 1),
('EXCELINDUS', 'NSE', 4),
('EXCELSOFT', 'NSE', 1),
('EXICOM', 'NSE', 5),
('EXIDEIND', 'NSE', 5),
('EXPLEOSOL', 'NSE', 5),
('FABTECH', 'NSE', 1),
('FACT', 'NSE', 5),
('FCL', 'NSE', 5),
('FDC', 'NSE', 4),
('FEDDERSHOL', 'NSE', 5),
('FEDERALBNK', 'NSE', 5),
('FEDFINA', 'NSE', 5),
('FERMENTA', 'NSE', 5),
('FIEMIND', 'NSE', 5),
('FILATEX', 'NSE', 5),
('FINCABLES', 'NSE', 5),
('FINEORG', 'NSE', 4),
('FINIETF', 'NSE', 1),
('FINOPB', 'NSE', 4),
('FINPIPE', 'NSE', 5),
('FIRSTCRY', 'NSE', 5),
('FISCHER', 'NSE', 4),
('FIVESTAR', 'NSE', 5),
('FLAIR', 'NSE', 4),
('FLUOROCHEM', 'NSE', 5),
('FMCGIETF', 'NSE', 4),
('FMGOETZE', 'NSE', 4),
('FORCEMOT', 'NSE', 5),
('FORTIS', 'NSE', 5),
('FOSECOIND', 'NSE', 4),
('FRACTAL', 'NSE', 5),
('FRONTSP', 'NSE', 4),
('FSL', 'NSE', 5),
('FUSION', 'NSE', 5),
('GABRIEL', 'NSE', 5),
('GAEL', 'NSE', 5),
('GAIL', 'NSE', 5),
('GALAPREC', 'NSE', 4),
('GALAXYSURF', 'NSE', 5),
('GANDHAR', 'NSE', 5),
('GANECOS', 'NSE', 5),
('GANESHCP', 'NSE', 4),
('GANESHHOU', 'NSE', 5),
('GARFIBRES', 'NSE', 4),
('GARUDA', 'NSE', 4),
('GATEWAY', 'NSE', 4),
('GCSL', 'NSE', 5),
('GEMAROMA', 'NSE', 1),
('GENCON', 'NSE', 1),
('GENESYS', 'NSE', 4),
('GENUSPOWER', 'NSE', 5),
('GEOJITFSL', 'NSE', 4),
('GESHIP', 'NSE', 5),
('GHCL', 'NSE', 5),
('GHCLTEXTIL', 'NSE', 5),
('GICRE', 'NSE', 5),
('GILLETTE', 'NSE', 5),
('GIPCL', 'NSE', 4),
('GKENERGY', 'NSE', 5),
('GKSL', 'NSE', 4),
('GLAND', 'NSE', 5),
('GLAXO', 'NSE', 5),
('GLENMARK', 'NSE', 5),
('GLOBALVECT', 'NSE', 1),
('GLOBUSSPR', 'NSE', 5),
('GMBREW', 'NSE', 4),
('GMDCLTD', 'NSE', 5),
('GMMPFAUDLR', 'NSE', 5),
('GMRAIRPORT', 'NSE', 5),
('GMRP&UI', 'NSE', 4),
('GNA', 'NSE', 5),
('GNFC', 'NSE', 5),
('GOCLCORP', 'NSE', 4),
('GOCOLORS', 'NSE', 5),
('GODAVARIB', 'NSE', 4),
('GODFRYPHLP', 'NSE', 5),
('GODIGIT', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('GODREJAGRO', 'NSE', 5),
('GODREJCP', 'NSE', 5),
('GODREJIND', 'NSE', 5),
('GODREJPROP', 'NSE', 5),
('GOKEX', 'NSE', 5),
('GOKULAGRO', 'NSE', 5),
('GOLD1', 'NSE', 5),
('GOLDADD', 'NSE', 1),
('GOLDAXIS', 'NSE', 5),
('GOLDBEES', 'NSE', 5),
('GOLDBETA', 'NSE', 1),
('GOLDCASE', 'NSE', 5),
('GOLDETF', 'NSE', 5),
('GOLDIAM', 'NSE', 5),
('GOLDIETF', 'NSE', 5),
('GOODLUCK', 'NSE', 5),
('GOODYEAR', 'NSE', 4),
('GOPAL', 'NSE', 4),
('GPIL', 'NSE', 5),
('GPPL', 'NSE', 5),
('GPTHEALTH', 'NSE', 4),
('GPTINFRA', 'NSE', 4),
('GRANULES', 'NSE', 5),
('GRAPHITE', 'NSE', 5),
('GRASIM', 'NSE', 5),
('GRAUWEIL', 'NSE', 4),
('GRAVITA', 'NSE', 5),
('GREAVESCOT', 'NSE', 5),
('GREENLAM', 'NSE', 4),
('GREENPANEL', 'NSE', 4),
('GREENPLY', 'NSE', 5),
('GREENPOWER', 'NSE', 4),
('GRINDWELL', 'NSE', 4),
('GRINFRA', 'NSE', 4),
('GRMOVER', 'NSE', 4),
('GROWW', 'NSE', 5),
('GROWWDEFNC', 'NSE', 1),
('GROWWEV', 'NSE', 1),
('GROWWGOLD', 'NSE', 1),
('GROWWHOSPI', 'NSE', 1),
('GROWWPOWER', 'NSE', 1),
('GROWWRAIL', 'NSE', 1),
('GROWWSLVR', 'NSE', 1),
('GRPLTD', 'NSE', 1),
('GRSE', 'NSE', 5),
('GRWRHITECH', 'NSE', 5),
('GSFC', 'NSE', 5),
('GSPCROP', 'NSE', 5),
('GTLINFRA', 'NSE', 4),
('GUFICBIO', 'NSE', 4),
('GUJALKALI', 'NSE', 4),
('GUJENERGY', 'NSE', 5),
('GUJTHEM', 'NSE', 4),
('GULFOILLUB', 'NSE', 5),
('GULPOLY', 'NSE', 4),
('GVT&D', 'NSE', 5),
('GYFTR', 'NSE', 4),
('HAL', 'NSE', 5),
('HAPPSTMNDS', 'NSE', 5),
('HARDWYN', 'NSE', 1),
('HARIOMPIPE', 'NSE', 4),
('HARSHA', 'NSE', 4),
('HATHWAY', 'NSE', 4),
('HATSUN', 'NSE', 4),
('HAVELLS', 'NSE', 5),
('HAWKINCOOK', 'NSE', 4),
('HAZOOR', 'NSE', 1),
('HBLENGINE', 'NSE', 5),
('HCC', 'NSE', 5),
('HCG', 'NSE', 5),
('HCLTECH', 'NSE', 5),
('HDBFS', 'NSE', 5),
('HDFCAMC', 'NSE', 5),
('HDFCBANK', 'NSE', 5),
('HDFCBSE500', 'NSE', 1),
('HDFCGOLD', 'NSE', 5),
('HDFCGROWTH', 'NSE', 1),
('HDFCLIFE', 'NSE', 5),
('HDFCNEXT50', 'NSE', 4),
('HDFCNIFIT', 'NSE', 1),
('HDFCNIFTY', 'NSE', 1),
('HDFCNIMEG', 'NSE', 1),
('HDFCPVTBAN', 'NSE', 1),
('HDFCSILVER', 'NSE', 5),
('HDFCSML250', 'NSE', 5),
('HEALTHIETF', 'NSE', 1),
('HEG', 'NSE', 5),
('HEIDELBERG', 'NSE', 4),
('HEMIPROP', 'NSE', 4),
('HERITGFOOD', 'NSE', 5),
('HEROMOTOCO', 'NSE', 5),
('HESTERBIO', 'NSE', 5),
('HEXT', 'NSE', 5),
('HGINFRA', 'NSE', 4),
('HGS', 'NSE', 1),
('HIKAL', 'NSE', 4),
('HIMATSEIDE', 'NSE', 1),
('HINDALCO', 'NSE', 5),
('HINDCOPPER', 'NSE', 5),
('HINDOILEXP', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('HINDPETRO', 'NSE', 5),
('HINDUNILVR', 'NSE', 5),
('HINDWAREAP', 'NSE', 4),
('HINDZINC', 'NSE', 5),
('HIRECT', 'NSE', 4),
('HITECH', 'NSE', 4),
('HLEGLAS', 'NSE', 5),
('HMAAGRO', 'NSE', 4),
('HNDFDS', 'NSE', 4),
('HNGSNGBEES', 'NSE', 4),
('HOMEFIRST', 'NSE', 5),
('HONASA', 'NSE', 5),
('HONAUT', 'NSE', 5),
('HONDAPOWER', 'NSE', 4),
('HPL', 'NSE', 4),
('HSCL', 'NSE', 5),
('HUBTOWN', 'NSE', 5),
('HUDCO', 'NSE', 5),
('HUHTAMAKI', 'NSE', 5),
('HYUNDAI', 'NSE', 5),
('ICEMAKE', 'NSE', 4),
('ICICIAMC', 'NSE', 5),
('ICICIB22', 'NSE', 4),
('ICICIBANK', 'NSE', 5),
('ICICIGI', 'NSE', 5),
('ICICIPRULI', 'NSE', 5),
('ICIL', 'NSE', 5),
('ICRA', 'NSE', 5),
('IDBI', 'NSE', 5),
('IDEA', 'NSE', 5),
('IDFCFIRSTB', 'NSE', 5),
('IEX', 'NSE', 5),
('IFBAGRO', 'NSE', 1),
('IFBIND', 'NSE', 5),
('IFCI', 'NSE', 5),
('IFGLEXPOR', 'NSE', 4),
('IGARASHI', 'NSE', 4),
('IGCL', 'NSE', 1),
('IGIL', 'NSE', 5),
('IGL', 'NSE', 5),
('IGPL', 'NSE', 4),
('IIFL', 'NSE', 5),
('IIFLCAPS', 'NSE', 5),
('IITL', 'NSE', 1),
('IKIO', 'NSE', 4),
('IKS', 'NSE', 5),
('IMAGICAA', 'NSE', 4),
('IMFA', 'NSE', 5),
('INA', 'NSE', 4),
('INDGN', 'NSE', 5),
('INDHOTEL', 'NSE', 5),
('INDIACEM', 'NSE', 5),
('INDIAMART', 'NSE', 5),
('INDIANB', 'NSE', 5),
('INDIANHUME', 'NSE', 4),
('INDIASHLTR', 'NSE', 5),
('INDIGO', 'NSE', 5),
('INDIGOPNTS', 'NSE', 5),
('INDIGRID', 'NSE', 5),
('INDIQUBE', 'NSE', 1),
('INDNIPPON', 'NSE', 4),
('INDOBORAX', 'NSE', 4),
('INDOCO', 'NSE', 5),
('INDOFARM', 'NSE', 1),
('INDOMIM', 'NSE', 5),
('INDORAMA', 'NSE', 4),
('INDOSTAR', 'NSE', 5),
('INDRAMEDCO', 'NSE', 5),
('INDSWFTLAB', 'NSE', 5),
('INDUSINDBK', 'NSE', 5),
('INDUSINVIT', 'NSE', 1),
('INDUSTOWER', 'NSE', 5),
('INFOBEAN', 'NSE', 5),
('INFRAIETF', 'NSE', 1),
('INFY', 'NSE', 5),
('INGERRAND', 'NSE', 5),
('INNOVACAP', 'NSE', 4),
('INOXGREEN', 'NSE', 5),
('INOXINDIA', 'NSE', 5),
('INOXWIND', 'NSE', 5),
('INSECTICID', 'NSE', 4),
('INTELLECT', 'NSE', 5),
('INTERARCH', 'NSE', 4),
('IOB', 'NSE', 5),
('IOC', 'NSE', 5),
('IOLCP', 'NSE', 4),
('IONEXCHANG', 'NSE', 5),
('IPCALAB', 'NSE', 5),
('IPL', 'NSE', 4),
('IRB', 'NSE', 5),
('IRBINVIT', 'NSE', 4),
('IRCON', 'NSE', 5),
('IRCTC', 'NSE', 5),
('IREDA', 'NSE', 5),
('IRFC', 'NSE', 5),
('IRISDOREME', 'NSE', 4),
('IRMENERGY', 'NSE', 4),
('ISGEC', 'NSE', 4),
('IT', 'NSE', 1),
('ITBEES', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('ITC', 'NSE', 5),
('ITCHOTELS', 'NSE', 5),
('ITDC', 'NSE', 4),
('ITETF', 'NSE', 1),
('ITI', 'NSE', 4),
('ITIETF', 'NSE', 5),
('IVALUE', 'NSE', 5),
('IXIGO', 'NSE', 5),
('J&KBANK', 'NSE', 5),
('JAGRAN', 'NSE', 4),
('JAGSNPHARM', 'NSE', 5),
('JAICORPLTD', 'NSE', 4),
('JAINREC', 'NSE', 5),
('JAMNAAUTO', 'NSE', 5),
('JARO', 'NSE', 4),
('JASH', 'NSE', 5),
('JAYKAY', 'NSE', 4),
('JAYNECOIND', 'NSE', 5),
('JBMA', 'NSE', 5),
('JGCHEM', 'NSE', 4),
('JINDALSAW', 'NSE', 5),
('JINDALSTEL', 'NSE', 5),
('JINDRILL', 'NSE', 5),
('JINDWORLD', 'NSE', 5),
('JIOFIN', 'NSE', 5),
('JISLJALEQS', 'NSE', 4),
('JKCEMENT', 'NSE', 5),
('JKIL', 'NSE', 4),
('JKLAKSHMI', 'NSE', 5),
('JKPAPER', 'NSE', 5),
('JKTYRE', 'NSE', 5),
('JLHL', 'NSE', 5),
('JMFINANCIL', 'NSE', 5),
('JNKINDIA', 'NSE', 5),
('JPPOWER', 'NSE', 5),
('JSFB', 'NSE', 5),
('JSL', 'NSE', 5),
('JSLL', 'NSE', 5),
('JSWCEMENT', 'NSE', 5),
('JSWDULUX', 'NSE', 4),
('JSWENERGY', 'NSE', 5),
('JSWHL', 'NSE', 4),
('JSWINFRA', 'NSE', 5),
('JSWSTEEL', 'NSE', 5),
('JTEKTINDIA', 'NSE', 5),
('JTLIND', 'NSE', 5),
('JUBLCPL', 'NSE', 1),
('JUBLFOOD', 'NSE', 5),
('JUBLINGREA', 'NSE', 5),
('JUBLPHARMA', 'NSE', 5),
('JUNIORBEES', 'NSE', 5),
('JUNIPER', 'NSE', 4),
('JUSTDIAL', 'NSE', 5),
('JWL', 'NSE', 5),
('JYOTHYLAB', 'NSE', 5),
('JYOTICNC', 'NSE', 5),
('JYOTISTRUC', 'NSE', 4),
('KABRAEXTRU', 'NSE', 5),
('KAJARIACER', 'NSE', 5),
('KALAMANDIR', 'NSE', 4),
('KALPATARU', 'NSE', 4),
('KALYANKJIL', 'NSE', 5),
('KAMAHOLD', 'NSE', 1),
('KANSAINER', 'NSE', 5),
('KAPSTON', 'NSE', 4),
('KARURVYSYA', 'NSE', 5),
('KAYNES', 'NSE', 5),
('KCP', 'NSE', 4),
('KDDL', 'NSE', 4),
('KEC', 'NSE', 5),
('KEI', 'NSE', 5),
('KELLTONTEC', 'NSE', 1),
('KENNAMET', 'NSE', 4),
('KERNEX', 'NSE', 5),
('KFINTECH', 'NSE', 5),
('KICL', 'NSE', 1),
('KIMS', 'NSE', 5),
('KINGFA', 'NSE', 5),
('KIOCL', 'NSE', 5),
('KIRIINDUS', 'NSE', 5),
('KIRLFER', 'NSE', 4),
('KIRLOSBROS', 'NSE', 5),
('KIRLOSENG', 'NSE', 5),
('KIRLOSIND', 'NSE', 4),
('KIRLPNU', 'NSE', 5),
('KISSHT', 'NSE', 5),
('KITEX', 'NSE', 4),
('KKCL', 'NSE', 4),
('KLBRENG', 'NSE', 4),
('KMCSHIL', 'NSE', 4),
('KMEW', 'NSE', 5),
('KNACK', 'NSE', 5),
('KNRCON', 'NSE', 5),
('KOLTEPATIL', 'NSE', 4),
('KOPRAN', 'NSE', 1),
('KOTAKBANK', 'NSE', 5),
('KOTHARIPET', 'NSE', 1),
('KOVAI', 'NSE', 4),
('KPEL', 'NSE', 5),
('KPIGREEN', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('KPIL', 'NSE', 5),
('KPITTECH', 'NSE', 5),
('KPL', 'NSE', 5),
('KPRMILL', 'NSE', 5),
('KRBL', 'NSE', 5),
('KRISHANA', 'NSE', 5),
('KRISHNADEF', 'NSE', 5),
('KROSS', 'NSE', 5),
('KRSNAA', 'NSE', 4),
('KRT', 'NSE', 1),
('KSB', 'NSE', 5),
('KSCL', 'NSE', 5),
('KSHINTL', 'NSE', 5),
('KSL', 'NSE', 4),
('KSOLVES', 'NSE', 1),
('KTKBANK', 'NSE', 5),
('KUSUMGAR', 'NSE', 5),
('KWIL', 'NSE', 5),
('LALPATHLAB', 'NSE', 5),
('LANDMARK', 'NSE', 5),
('LAOPALA', 'NSE', 4),
('LASERPOWER', 'NSE', 5),
('LATENTVIEW', 'NSE', 5),
('LAURUSLABS', 'NSE', 5),
('LAXMIDENTL', 'NSE', 4),
('LCL', 'NSE', 5),
('LEMONTREE', 'NSE', 5),
('LENSKART', 'NSE', 5),
('LGBBROSLTD', 'NSE', 4),
('LGEINDIA', 'NSE', 5),
('LGHL', 'NSE', 1),
('LIBERTSHOE', 'NSE', 1),
('LICHSGFIN', 'NSE', 5),
('LICI', 'NSE', 5),
('LINCOLN', 'NSE', 1),
('LINDEINDIA', 'NSE', 5),
('LLOYDSENGG', 'NSE', 5),
('LLOYDSENT', 'NSE', 5),
('LLOYDSME', 'NSE', 5),
('LMW', 'NSE', 5),
('LODHA', 'NSE', 5),
('LORDSCHLO', 'NSE', 1),
('LOWVOL1', 'NSE', 1),
('LOWVOLIETF', 'NSE', 4),
('LT', 'NSE', 5),
('LTF', 'NSE', 5),
('LTFOODS', 'NSE', 5),
('LTM', 'NSE', 5),
('LTTS', 'NSE', 5),
('LUMAXIND', 'NSE', 5),
('LUMAXTECH', 'NSE', 5),
('LUPIN', 'NSE', 5),
('LUXIND', 'NSE', 4),
('LXCHEM', 'NSE', 5),
('M&M', 'NSE', 5),
('M&MFIN', 'NSE', 5),
('MAANALU', 'NSE', 1),
('MACPOWER', 'NSE', 5),
('MAFANG', 'NSE', 2),
('MAHABANK', 'NSE', 5),
('MAHKTECH', 'NSE', 1),
('MAHLIFE', 'NSE', 5),
('MAHLOG', 'NSE', 5),
('MAHSCOOTER', 'NSE', 5),
('MAHSEAMLES', 'NSE', 4),
('MAITHANALL', 'NSE', 4),
('MAMATA', 'NSE', 4),
('MANAKCOAT', 'NSE', 4),
('MANALIPETC', 'NSE', 4),
('MANAPPURAM', 'NSE', 5),
('MANBA', 'NSE', 5),
('MANCREDIT', 'NSE', 5),
('MANGLMCEM', 'NSE', 4),
('MANINDS', 'NSE', 5),
('MANINFRA', 'NSE', 4),
('MANKIND', 'NSE', 5),
('MANOMAY', 'NSE', 1),
('MANORAMA', 'NSE', 5),
('MANYAVAR', 'NSE', 5),
('MAPMYINDIA', 'NSE', 5),
('MARATHON', 'NSE', 4),
('MARICO', 'NSE', 5),
('MARINE', 'NSE', 5),
('MARKOLINES', 'NSE', 1),
('MARKSANS', 'NSE', 5),
('MARSONS', 'NSE', 5),
('MARUTI', 'NSE', 5),
('MASFIN', 'NSE', 5),
('MASTEK', 'NSE', 5),
('MASTERTR', 'NSE', 4),
('MAXESTATES', 'NSE', 4),
('MAXHEALTH', 'NSE', 5),
('MAXIND', 'NSE', 1),
('MAYURUNIQ', 'NSE', 5),
('MAZDOCK', 'NSE', 5),
('MBAPL', 'NSE', 5),
('MBEL', 'NSE', 4),
('MCLOUD', 'NSE', 5),
('MCX', 'NSE', 5),
('MEDANTA', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('MEDIASSIST', 'NSE', 5),
('MEDICO', 'NSE', 1),
('MEDPLUS', 'NSE', 5),
('MEESHO', 'NSE', 5),
('MEIL', 'NSE', 1),
('METAL', 'NSE', 1),
('METALIETF', 'NSE', 4),
('METROBRAND', 'NSE', 4),
('METROPOLIS', 'NSE', 5),
('MFSL', 'NSE', 5),
('MGL', 'NSE', 5),
('MHRIL', 'NSE', 4),
('MID150BEES', 'NSE', 5),
('MID150CASE', 'NSE', 1),
('MIDCAPETF', 'NSE', 4),
('MIDCAPIETF', 'NSE', 1),
('MIDHANI', 'NSE', 5),
('MIDSMALL', 'NSE', 1),
('MIDWESTLTD', 'NSE', 4),
('MIIL', 'NSE', 4),
('MINDACORP', 'NSE', 5),
('MINDSPACE', 'NSE', 1),
('MMFL', 'NSE', 4),
('MMP', 'NSE', 1),
('MMTC', 'NSE', 5),
('MOBIKWIK', 'NSE', 5),
('MOCAPITAL', 'NSE', 1),
('MODEFENCE', 'NSE', 5),
('MODIS', 'NSE', 1),
('MOGOLD', 'NSE', 4),
('MOIL', 'NSE', 5),
('MOL', 'NSE', 5),
('MOLDTKPAC', 'NSE', 5),
('MOM100', 'NSE', 1),
('MOM30IETF', 'NSE', 1),
('MOMENTUM50', 'NSE', 1),
('MOMMIDCAP', 'NSE', 1),
('MON100', 'NSE', 2),
('MONARCH', 'NSE', 5),
('MONIFTY500', 'NSE', 1),
('MONTECARLO', 'NSE', 4),
('MOREALTY', 'NSE', 4),
('MOREPENLAB', 'NSE', 5),
('MOSCHIP', 'NSE', 5),
('MOSILVER', 'NSE', 1),
('MOSMALL250', 'NSE', 1),
('MOTHERSON', 'NSE', 5),
('MOTILALOFS', 'NSE', 5),
('MOTISONS', 'NSE', 5),
('MPHASIS', 'NSE', 5),
('MPSLTD', 'NSE', 4),
('MRF', 'NSE', 5),
('MRPL', 'NSE', 5),
('MSPL', 'NSE', 4),
('MSTCLTD', 'NSE', 5),
('MSUMI', 'NSE', 5),
('MTNL', 'NSE', 4),
('MUFIN', 'NSE', 5),
('MUKANDLTD', 'NSE', 1),
('MUNJALAU', 'NSE', 4),
('MUTHOOTFIN', 'NSE', 5),
('MUTHOOTMF', 'NSE', 5),
('MVGJL', 'NSE', 1),
('MWL', 'NSE', 1),
('NACLIND', 'NSE', 5),
('NAM', 'NSE', 5),
('NARMADA', 'NSE', 5),
('NATCOPHARM', 'NSE', 5),
('NATIONALUM', 'NSE', 5),
('NAUKRI', 'NSE', 5),
('NAVA', 'NSE', 5),
('NAVINFLUOR', 'NSE', 5),
('NAVKARCORP', 'NSE', 4),
('NAVNETEDUL', 'NSE', 4),
('NAZARA', 'NSE', 5),
('NBCC', 'NSE', 5),
('NCC', 'NSE', 5),
('NDRAUTO', 'NSE', 4),
('NELCAST', 'NSE', 4),
('NELCO', 'NSE', 5),
('NEOGEN', 'NSE', 5),
('NEPHROPLUS', 'NSE', 5),
('NESCO', 'NSE', 5),
('NESTLEIND', 'NSE', 5),
('NETWEB', 'NSE', 5),
('NETWORK18', 'NSE', 5),
('NEULANDLAB', 'NSE', 5),
('NEWGEN', 'NSE', 5),
('NEXT50', 'NSE', 1),
('NEXT50BETA', 'NSE', 1),
('NEXT50IETF', 'NSE', 4),
('NFL', 'NSE', 4),
('NGLFINE', 'NSE', 4),
('NH', 'NSE', 5),
('NHIT', 'NSE', 5),
('NHPC', 'NSE', 5),
('NIACL', 'NSE', 5),
('NIBE', 'NSE', 5),
('NIF100BEES', 'NSE', 1),
('NIFTY1', 'NSE', 1);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('NIFTYBEES', 'NSE', 5),
('NIFTYBETA', 'NSE', 1),
('NIFTYETF', 'NSE', 4),
('NIFTYIETF', 'NSE', 5),
('NIITLTD', 'NSE', 4),
('NIITMTS', 'NSE', 4),
('NILKAMAL', 'NSE', 5),
('NITCO', 'NSE', 5),
('NITINSPIN', 'NSE', 4),
('NITTAGELA', 'NSE', 4),
('NIVABUPA', 'NSE', 5),
('NLCINDIA', 'NSE', 5),
('NMDC', 'NSE', 5),
('NOCIL', 'NSE', 5),
('NORTHARC', 'NSE', 5),
('NOVARTIND', 'NSE', 4),
('NPST', 'NSE', 4),
('NRBBEARING', 'NSE', 5),
('NSIL', 'NSE', 4),
('NSLNISP', 'NSE', 5),
('NTPC', 'NSE', 5),
('NTPCGREEN', 'NSE', 5),
('NUCLEUS', 'NSE', 4),
('NUVAMA', 'NSE', 5),
('NUVOCO', 'NSE', 5),
('NXST', 'NSE', 4),
('NYKAA', 'NSE', 5),
('OAL', 'NSE', 4),
('OBEROIRLTY', 'NSE', 5),
('OFSS', 'NSE', 5),
('OIL', 'NSE', 5),
('OILIETF', 'NSE', 1),
('OLAELEC', 'NSE', 5),
('OLECTRA', 'NSE', 5),
('OMAXE', 'NSE', 4),
('OMINFRAL', 'NSE', 1),
('OMNI', 'NSE', 5),
('OMPOWER', 'NSE', 1),
('ONEPOINT', 'NSE', 4),
('ONESOURCE', 'NSE', 5),
('ONGC', 'NSE', 5),
('ONWARDTEC', 'NSE', 4),
('OPTIEMUS', 'NSE', 5),
('ORCHPHARMA', 'NSE', 4),
('ORIENTCEM', 'NSE', 4),
('ORIENTELEC', 'NSE', 5),
('ORIENTHOT', 'NSE', 4),
('ORIENTTECH', 'NSE', 5),
('ORISSAMINE', 'NSE', 5),
('ORKLAINDIA', 'NSE', 4),
('OSWALGREEN', 'NSE', 1),
('OSWALPUMPS', 'NSE', 5),
('PACEDIGITK', 'NSE', 5),
('PAGEIND', 'NSE', 5),
('PAISALO', 'NSE', 5),
('PANACEABIO', 'NSE', 4),
('PANAMAPET', 'NSE', 4),
('PANORAMA', 'NSE', 4),
('PANSARI', 'NSE', 1),
('PARACABLES', 'NSE', 5),
('PARADEEP', 'NSE', 5),
('PARAGMILK', 'NSE', 5),
('PARAS', 'NSE', 5),
('PARKHOSPS', 'NSE', 5),
('PARKHOTELS', 'NSE', 4),
('PATANJALI', 'NSE', 5),
('PATELENG', 'NSE', 5),
('PATELRMART', 'NSE', 1),
('PAUSHAKLTD', 'NSE', 5),
('PAYTM', 'NSE', 5),
('PCBL', 'NSE', 5),
('PCJEWELLER', 'NSE', 5),
('PDMJEPAPER', 'NSE', 1),
('PDSL', 'NSE', 5),
('PENIND', 'NSE', 4),
('PERSISTENT', 'NSE', 5),
('PETRONET', 'NSE', 5),
('PFC', 'NSE', 5),
('PFIZER', 'NSE', 5),
('PFOCUS', 'NSE', 5),
('PFS', 'NSE', 4),
('PGEL', 'NSE', 5),
('PGHH', 'NSE', 5),
('PGHL', 'NSE', 5),
('PGIL', 'NSE', 5),
('PGINVIT', 'NSE', 5),
('PHARMABEES', 'NSE', 5),
('PHOENIXLTD', 'NSE', 5),
('PICCADIL', 'NSE', 5),
('PIDILITIND', 'NSE', 5),
('PIIND', 'NSE', 5),
('PINELABS', 'NSE', 5),
('PIRAMALFIN', 'NSE', 5),
('PITTIENG', 'NSE', 4),
('PIXTRANS', 'NSE', 4),
('PLATIND', 'NSE', 4),
('PNB', 'NSE', 5),
('PNBGILTS', 'NSE', 4),
('PNBHOUSING', 'NSE', 5),
('PNCINFRA', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('PNGJL', 'NSE', 5),
('PNGSREVA', 'NSE', 5),
('POCL', 'NSE', 5),
('POKARNA', 'NSE', 4),
('POLICYBZR', 'NSE', 5),
('POLYCAB', 'NSE', 5),
('POLYMED', 'NSE', 5),
('POLYPLEX', 'NSE', 5),
('POONAWALLA', 'NSE', 5),
('POWERGRID', 'NSE', 5),
('POWERICA', 'NSE', 4),
('POWERINDIA', 'NSE', 5),
('POWERMECH', 'NSE', 5),
('PPLPHARMA', 'NSE', 5),
('PRABHA', 'NSE', 1),
('PRAJIND', 'NSE', 5),
('PRAKASH', 'NSE', 4),
('PRAVEG', 'NSE', 1),
('PRECAM', 'NSE', 4),
('PRECWIRE', 'NSE', 5),
('PREMEXPLN', 'NSE', 5),
('PREMIERENE', 'NSE', 5),
('PREMIERPOL', 'NSE', 1),
('PRESTIGE', 'NSE', 5),
('PRICOLLTD', 'NSE', 5),
('PRIMO', 'NSE', 1),
('PRINCEPIPE', 'NSE', 4),
('PRIVISCL', 'NSE', 5),
('PROSTARM', 'NSE', 1),
('PROTEAN', 'NSE', 5),
('PRSMJOHNSN', 'NSE', 4),
('PRUDENT', 'NSE', 5),
('PSB', 'NSE', 4),
('PSPPROJECT', 'NSE', 5),
('PSUBANK', 'NSE', 1),
('PSUBNKBEES', 'NSE', 5),
('PTC', 'NSE', 5),
('PTCIL', 'NSE', 5),
('PUNJABCHEM', 'NSE', 4),
('PURVA', 'NSE', 4),
('PVRINOX', 'NSE', 5),
('PVTBANIETF', 'NSE', 4),
('PWL', 'NSE', 5),
('PYRAMID', 'NSE', 4),
('QGOLDHALF', 'NSE', 1),
('QUADFUTURE', 'NSE', 4),
('QUESS', 'NSE', 5),
('RACLGEAR', 'NSE', 4),
('RADHIKAJWE', 'NSE', 5),
('RADICO', 'NSE', 5),
('RAILTEL', 'NSE', 5),
('RAIN', 'NSE', 5),
('RAINBOW', 'NSE', 5),
('RAJRATAN', 'NSE', 5),
('RALLIS', 'NSE', 5),
('RAMBHAJO', 'NSE', 4),
('RAMCOCEM', 'NSE', 5),
('RAMCOIND', 'NSE', 4),
('RAMKY', 'NSE', 4),
('RAMRAT', 'NSE', 5),
('RANEHOLDIN', 'NSE', 4),
('RATEGAIN', 'NSE', 5),
('RATNAMANI', 'NSE', 5),
('RATNAVEER', 'NSE', 5),
('RAYMOND', 'NSE', 5),
('RAYMONDLSL', 'NSE', 5),
('RAYMONDREL', 'NSE', 5),
('RBA', 'NSE', 5),
('RBLBANK', 'NSE', 5),
('RBZJEWEL', 'NSE', 1),
('RCF', 'NSE', 5),
('RECLTD', 'NSE', 5),
('REDINGTON', 'NSE', 5),
('REDTAPE', 'NSE', 4),
('REFEX', 'NSE', 5),
('RELAXO', 'NSE', 4),
('RELIANCE', 'NSE', 5),
('RELIGARE', 'NSE', 5),
('RELTD', 'NSE', 4),
('RENUKA', 'NSE', 4),
('REPCOHOME', 'NSE', 4),
('RESPONIND', 'NSE', 4),
('RGL', 'NSE', 4),
('RHETAN', 'NSE', 5),
('RHIM', 'NSE', 5),
('RICOAUTO', 'NSE', 5),
('RIIL', 'NSE', 4),
('RIIT', 'NSE', 5),
('RIR', 'NSE', 4),
('RISHABH', 'NSE', 5),
('RITCO', 'NSE', 4),
('RITES', 'NSE', 5),
('RKFORGE', 'NSE', 5),
('RMC', 'NSE', 1),
('RML', 'NSE', 4),
('ROLEXRINGS', 'NSE', 5),
('ROSSARI', 'NSE', 4),
('ROSSTECH', 'NSE', 5),
('ROTO', 'NSE', 4),
('ROUTE', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('RPEL', 'NSE', 5),
('RPGLIFE', 'NSE', 5),
('RPOWER', 'NSE', 5),
('RPSGVENT', 'NSE', 4),
('RPTECH', 'NSE', 5),
('RRKABEL', 'NSE', 5),
('RSL', 'NSE', 4),
('RSYSTEMS', 'NSE', 5),
('RTNINDIA', 'NSE', 4),
('RTNPOWER', 'NSE', 5),
('RUBICON', 'NSE', 5),
('RUPA', 'NSE', 4),
('RUSHIL', 'NSE', 1),
('RUSTOMJEE', 'NSE', 1),
('RVNL', 'NSE', 5),
('SAATVIKGL', 'NSE', 4),
('SAFARI', 'NSE', 5),
('SAGCEM', 'NSE', 4),
('SAGILITY', 'NSE', 5),
('SAIL', 'NSE', 5),
('SAILIFE', 'NSE', 5),
('SAIPARENT', 'NSE', 4),
('SAKAR', 'NSE', 5),
('SAKSOFT', 'NSE', 4),
('SALASAR', 'NSE', 4),
('SALZERELEC', 'NSE', 4),
('SAMBHV', 'NSE', 5),
('SAMHI', 'NSE', 5),
('SAMMAANCAP', 'NSE', 5),
('SANATHAN', 'NSE', 4),
('SANDHAR', 'NSE', 5),
('SANDUMA', 'NSE', 5),
('SANGAMIND', 'NSE', 4),
('SANGHVIMOV', 'NSE', 5),
('SANOFI', 'NSE', 5),
('SANOFICONR', 'NSE', 5),
('SANSERA', 'NSE', 5),
('SANSTAR', 'NSE', 4),
('SAPPHIRE', 'NSE', 5),
('SARDAEN', 'NSE', 5),
('SAREGAMA', 'NSE', 5),
('SATIN', 'NSE', 5),
('SAURASHCEM', 'NSE', 1),
('SBCL', 'NSE', 5),
('SBFC', 'NSE', 5),
('SBICARD', 'NSE', 5),
('SBIETFIT', 'NSE', 1),
('SBIETFPB', 'NSE', 1),
('SBIFUNDS', 'NSE', 5),
('SBILIFE', 'NSE', 5),
('SBIN', 'NSE', 5),
('SBISILVER', 'NSE', 5),
('SCHAEFFLER', 'NSE', 5),
('SCHNEIDER', 'NSE', 5),
('SCI', 'NSE', 5),
('SCILAL', 'NSE', 1),
('SCODATUBES', 'NSE', 1),
('SDBL', 'NSE', 4),
('SEAMECLTD', 'NSE', 5),
('SEDEMAC', 'NSE', 5),
('SEIL', 'NSE', 5),
('SENCO', 'NSE', 5),
('SENORES', 'NSE', 5),
('SENSEXIETF', 'NSE', 1),
('SEPC', 'NSE', 4),
('SERVOTECH', 'NSE', 5),
('SESHAPAPER', 'NSE', 5),
('SETFGOLD', 'NSE', 5),
('SETFNIF50', 'NSE', 5),
('SETFNIFBK', 'NSE', 1),
('SETFNN50', 'NSE', 1),
('SFL', 'NSE', 5),
('SGFIN', 'NSE', 5),
('SGMART', 'NSE', 5),
('SHADOWFAX', 'NSE', 5),
('SHAH', 'NSE', 4),
('SHAILY', 'NSE', 5),
('SHAKTIPUMP', 'NSE', 5),
('SHALBY', 'NSE', 1),
('SHANKARA', 'NSE', 1),
('SHANTIGEAR', 'NSE', 4),
('SHANTIGOLD', 'NSE', 5),
('SHARDACROP', 'NSE', 5),
('SHARDAMOTR', 'NSE', 5),
('SHAREINDIA', 'NSE', 4),
('SHILCTECH', 'NSE', 5),
('SHILPAMED', 'NSE', 5),
('SHINDL', 'NSE', 1),
('SHK', 'NSE', 5),
('SHOPERSTOP', 'NSE', 4),
('SHREDIGCEM', 'NSE', 1),
('SHREECEM', 'NSE', 5),
('SHREEJISPG', 'NSE', 5),
('SHREEPUSHK', 'NSE', 1),
('SHRINGARMS', 'NSE', 5),
('SHRIPISTON', 'NSE', 5),
('SHRIRAMFIN', 'NSE', 5),
('SHRIRAMPPS', 'NSE', 4),
('SHUKRAPHAR', 'NSE', 1),
('SHYAMMETL', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('SIEMENS', 'NSE', 5),
('SIGACHI', 'NSE', 1),
('SIGMA', 'NSE', 4),
('SIGNATURE', 'NSE', 5),
('SIGNPOST', 'NSE', 4),
('SIKA', 'NSE', 4),
('SILVER', 'NSE', 5),
('SILVER1', 'NSE', 5),
('SILVERADD', 'NSE', 1),
('SILVERAG', 'NSE', 1),
('SILVERAXIS', 'NSE', 4),
('SILVERBEES', 'NSE', 5),
('SILVERBETA', 'NSE', 4),
('SILVERCASE', 'NSE', 5),
('SILVERIETF', 'NSE', 5),
('SIMPLEXINF', 'NSE', 4),
('SINDHUTRAD', 'NSE', 4),
('SIRCA', 'NSE', 5),
('SIS', 'NSE', 4),
('SIYSIL', 'NSE', 4),
('SJS', 'NSE', 5),
('SJVN', 'NSE', 5),
('SKFINDIA', 'NSE', 4),
('SKFINDUS', 'NSE', 5),
('SKIPPER', 'NSE', 5),
('SKMEGGPROD', 'NSE', 5),
('SKYGOLD', 'NSE', 5),
('SMALLCAP', 'NSE', 4),
('SMARTWORKS', 'NSE', 5),
('SMCGLOBAL', 'NSE', 4),
('SML100CASE', 'NSE', 1),
('SMLMAH', 'NSE', 5),
('SMSPHARMA', 'NSE', 5),
('SOBHA', 'NSE', 5),
('SOLARA', 'NSE', 5),
('SOLARINDS', 'NSE', 5),
('SOLARWORLD', 'NSE', 4),
('SOLEX', 'NSE', 1),
('SOMANYCERA', 'NSE', 5),
('SONACOMS', 'NSE', 5),
('SONATSOFTW', 'NSE', 5),
('SOTL', 'NSE', 4),
('SOUTHBANK', 'NSE', 5),
('SOUTHWEST', 'NSE', 1),
('SPAL', 'NSE', 5),
('SPANDANA', 'NSE', 5),
('SPARC', 'NSE', 4),
('SPIC', 'NSE', 4),
('SPLPETRO', 'NSE', 5),
('SPMLINFRA', 'NSE', 4),
('SPORTKING', 'NSE', 5),
('SRF', 'NSE', 5),
('SRM', 'NSE', 4),
('SSWL', 'NSE', 5),
('STANLEY', 'NSE', 1),
('STAR', 'NSE', 5),
('STARCEMENT', 'NSE', 4),
('STARHEALTH', 'NSE', 5),
('STEELCAS', 'NSE', 4),
('STEELXIND', 'NSE', 4),
('STOVEKRAFT', 'NSE', 5),
('STUDDS', 'NSE', 4),
('STYL', 'NSE', 5),
('STYLAMIND', 'NSE', 5),
('STYRENIX', 'NSE', 5),
('SUBEXLTD', 'NSE', 1),
('SUBROS', 'NSE', 5),
('SUDARSCHEM', 'NSE', 5),
('SUKHJITS', 'NSE', 1),
('SULA', 'NSE', 5),
('SUMICHEM', 'NSE', 5),
('SUNCLAY', 'NSE', 4),
('SUNDARMFIN', 'NSE', 5),
('SUNDRMFAST', 'NSE', 5),
('SUNDROP', 'NSE', 4),
('SUNFLAG', 'NSE', 5),
('SUNPHARMA', 'NSE', 5),
('SUNTECK', 'NSE', 5),
('SUNTV', 'NSE', 5),
('SUPRAJIT', 'NSE', 4),
('SUPREMEIND', 'NSE', 5),
('SUPRIYA', 'NSE', 5),
('SURAKSHA', 'NSE', 1),
('SURYAROSNI', 'NSE', 5),
('SURYODAY', 'NSE', 5),
('SUVEN', 'NSE', 5),
('SUYOG', 'NSE', 4),
('SUZLON', 'NSE', 5),
('SWANCORP', 'NSE', 5),
('SWARAJENG', 'NSE', 4),
('SWIGGY', 'NSE', 5),
('SWSOLAR', 'NSE', 5),
('SYMPHONY', 'NSE', 4),
('SYNCOMF', 'NSE', 4),
('SYNGENE', 'NSE', 5),
('SYRMA', 'NSE', 5),
('TAALTECH', 'NSE', 1),
('TAJGVK', 'NSE', 5),
('TALBROAUTO', 'NSE', 4),
('TANLA', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('TARC', 'NSE', 5),
('TARIL', 'NSE', 5),
('TARSONS', 'NSE', 4),
('TASTYBITE', 'NSE', 4),
('TATACAP', 'NSE', 5),
('TATACHEM', 'NSE', 5),
('TATACOMM', 'NSE', 5),
('TATACONSUM', 'NSE', 5),
('TATAELXSI', 'NSE', 5),
('TATAGOLD', 'NSE', 5),
('TATAINVEST', 'NSE', 5),
('TATAPOWER', 'NSE', 5),
('TATASTEEL', 'NSE', 5),
('TATATECH', 'NSE', 5),
('TATSILV', 'NSE', 5),
('TATVA', 'NSE', 5),
('TBOTEK', 'NSE', 5),
('TBZ', 'NSE', 5),
('TCC', 'NSE', 4),
('TCI', 'NSE', 5),
('TCIEXP', 'NSE', 4),
('TCPLPACK', 'NSE', 1),
('TCS', 'NSE', 5),
('TDPOWERSYS', 'NSE', 5),
('TEAMLEASE', 'NSE', 5),
('TECHM', 'NSE', 5),
('TECHNOE', 'NSE', 5),
('TEGA', 'NSE', 5),
('TEJASNET', 'NSE', 5),
('TEMBO', 'NSE', 5),
('TENNIND', 'NSE', 5),
('TEXINFRA', 'NSE', 4),
('TEXRAIL', 'NSE', 5),
('TFCILTD', 'NSE', 5),
('TGVSL', 'NSE', 4),
('THEJO', 'NSE', 4),
('THELEELA', 'NSE', 5),
('THERMAX', 'NSE', 5),
('THOMASCOOK', 'NSE', 5),
('THOMASCOTT', 'NSE', 1),
('THYROCARE', 'NSE', 5),
('TI', 'NSE', 5),
('TIIL', 'NSE', 4),
('TIINDIA', 'NSE', 5),
('TIMETECHNO', 'NSE', 5),
('TIMEX', 'NSE', 5),
('TIMKEN', 'NSE', 5),
('TINNARUBR', 'NSE', 4),
('TIPSFILMS', 'NSE', 1),
('TIPSMUSIC', 'NSE', 5),
('TIRUMALCHM', 'NSE', 5),
('TITAGARH', 'NSE', 5),
('TITAN', 'NSE', 5),
('TMB', 'NSE', 5),
('TMCV', 'NSE', 5),
('TMPV', 'NSE', 5),
('TNIDETF', 'NSE', 1),
('TNPETRO', 'NSE', 1),
('TNPL', 'NSE', 4),
('TOP10ADD', 'NSE', 4),
('TORNTPHARM', 'NSE', 5),
('TORNTPOWER', 'NSE', 5),
('TRANSRAILL', 'NSE', 5),
('TRAVELFOOD', 'NSE', 4),
('TRENT', 'NSE', 5),
('TRF', 'NSE', 1),
('TRIDENT', 'NSE', 5),
('TRITURBINE', 'NSE', 5),
('TRIVENI', 'NSE', 4),
('TRUALT', 'NSE', 5),
('TSFINV', 'NSE', 4),
('TTKHLTCARE', 'NSE', 4),
('TTKPRESTIG', 'NSE', 5),
('TTML', 'NSE', 5),
('TURTLEMINT', 'NSE', 5),
('TVSELECT', 'NSE', 1),
('TVSHLTD', 'NSE', 5),
('TVSMOTOR', 'NSE', 5),
('TVSSCS', 'NSE', 4),
('TVSSRICHAK', 'NSE', 4),
('UBL', 'NSE', 5),
('UCOBANK', 'NSE', 5),
('UDS', 'NSE', 4),
('UFLEX', 'NSE', 4),
('UGARSUGAR', 'NSE', 1),
('UGROCAP', 'NSE', 1),
('UJJIVANSFB', 'NSE', 5),
('ULTRACEMCO', 'NSE', 5),
('ULTRAMAR', 'NSE', 4),
('UNICHEMLAB', 'NSE', 4),
('UNIECOM', 'NSE', 1),
('UNIMECH', 'NSE', 5),
('UNIONBANK', 'NSE', 5),
('UNIPARTS', 'NSE', 5),
('UNITDSPR', 'NSE', 5),
('UNITECH', 'NSE', 4),
('UNIVCABLES', 'NSE', 5),
('UNOMINDA', 'NSE', 5),
('UPL', 'NSE', 5),
('URBANCO', 'NSE', 5);""",
        r"""INSERT OR IGNORE INTO intraday_leverage (symbol, exchange, multiplier) VALUES
('USHAMART', 'NSE', 5),
('UTIAMC', 'NSE', 5),
('UTKARSHBNK', 'NSE', 4),
('V2RETAIL', 'NSE', 5),
('VADILALIND', 'NSE', 5),
('VAIBHAVGBL', 'NSE', 5),
('VAML', 'NSE', 5),
('VARROC', 'NSE', 5),
('VBL', 'NSE', 5),
('VEDL', 'NSE', 5),
('VEDPOWER', 'NSE', 5),
('VEEDOL', 'NSE', 4),
('VENKEYS', 'NSE', 5),
('VENUSPIPES', 'NSE', 5),
('VERANDA', 'NSE', 5),
('VERTIS', 'NSE', 4),
('VESUVIUS', 'NSE', 4),
('VGUARD', 'NSE', 5),
('VIDHIING', 'NSE', 4),
('VIJAYA', 'NSE', 5),
('VIKRAMSOLR', 'NSE', 5),
('VIKRAN', 'NSE', 5),
('VIMTALABS', 'NSE', 5),
('VINATIORGA', 'NSE', 5),
('VINCOFE', 'NSE', 5),
('VINDHYATEL', 'NSE', 4),
('VIPIND', 'NSE', 4),
('VISAKAIND', 'NSE', 1),
('VISHNU', 'NSE', 5),
('VIYASH', 'NSE', 5),
('VMART', 'NSE', 5),
('VMM', 'NSE', 5),
('VOEPL', 'NSE', 4),
('VOGL', 'NSE', 5),
('VOLTAMP', 'NSE', 5),
('VOLTAS', 'NSE', 5),
('VRLLOG', 'NSE', 5),
('VSSL', 'NSE', 4),
('VSTIND', 'NSE', 5),
('VSTTILLERS', 'NSE', 4),
('VTL', 'NSE', 5),
('WAAREEENER', 'NSE', 5),
('WAAREERTL', 'NSE', 5),
('WABAG', 'NSE', 5),
('WAKEFIT', 'NSE', 5),
('WALCHANNAG', 'NSE', 5),
('WANBURY', 'NSE', 4),
('WELCORP', 'NSE', 5),
('WELENT', 'NSE', 5),
('WELSPLSOL', 'NSE', 4),
('WELSPUNLIV', 'NSE', 5),
('WENDT', 'NSE', 5),
('WESTLIFE', 'NSE', 4),
('WEWORK', 'NSE', 5),
('WHEELS', 'NSE', 5),
('WHIRLPOOL', 'NSE', 5),
('WINDLAS', 'NSE', 4),
('WINDMACHIN', 'NSE', 4),
('WIPRO', 'NSE', 5),
('WOCKPHARMA', 'NSE', 5),
('WONDERLA', 'NSE', 4),
('WPIL', 'NSE', 4),
('WSTCSTPAPR', 'NSE', 5),
('XCHANGING', 'NSE', 1),
('XPROINDIA', 'NSE', 5),
('XTRANET', 'NSE', 5),
('YASHO', 'NSE', 5),
('YATHARTH', 'NSE', 5),
('YATRA', 'NSE', 4),
('YESBANK', 'NSE', 5),
('ZAGGLE', 'NSE', 5),
('ZEEL', 'NSE', 5),
('ZENSARTECH', 'NSE', 5),
('ZENTEC', 'NSE', 5),
('ZFCVINDIA', 'NSE', 5),
('ZOTA', 'NSE', 4),
('ZUARI', 'NSE', 4),
('ZYDUSLIFE', 'NSE', 5),
('ZYDUSWELL', 'NSE', 5);""",
    ]


def status(engine):
    """Report what exists without changing anything."""
    print()
    print("Intraday Leverage Migration Status")
    print("-" * 46)

    present = table_exists(engine, TABLE_NAME)
    print(f"  {TABLE_NAME:<34} {'present' if present else 'MISSING'}")

    if present:
        count = get_row_count(engine, TABLE_NAME)
        print(f"  {'row count':<34} {count}")

    print("-" * 46)
    if present:
        count = get_row_count(engine, TABLE_NAME)
        print(f"All changes applied. ({count} rows)")
    else:
        print("Migration needed.")
    return present


def main():
    """Run the migration"""
    parser = argparse.ArgumentParser(description="Intraday leverage table migration")
    parser.add_argument(
        "--status", action="store_true", help="Report status without changing anything"
    )
    args = parser.parse_args()

    print()
    print("Intraday Leverage Migration")
    print("-" * 46)

    try:
        db_url = get_database_url()
        print(f"Database: {db_url.split('://')[0]}://...")

        if "sqlite" in db_url:
            engine = create_engine(db_url, poolclass=NullPool)
        else:
            engine = create_engine(db_url)

        if args.status:
            return 0 if status(engine) else 1

        print()
        print("Creating table...")
        create_table(engine)

        print()
        print("Seeding data...")
        seed_data(engine)

        print()
        print("[OK] Intraday leverage migration completed successfully!")
        return 0

    except Exception as e:
        print(f"\n[ERROR] Migration failed: {e}")
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
