// Generated by frontend/scripts/generate-drawing-tools.mjs from the pinned package.
// Metadata keeps the menu independent of the lazily loaded drawing renderer.
export const DRAW_TOOL_METADATA: Readonly<Record<string, { name: string; path: string; text: boolean; fields?: readonly string[] }>> = {
  "trend-line": {
    "name": "Trend Line",
    "path": "M6 18 18 6M5 18a1 1 0 0 0 2 0a1 1 0 0 0 -2 0zM17 6a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "ray": {
    "name": "Ray",
    "path": "M4 18 22 6M3 18a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "extended-line": {
    "name": "Extended Line",
    "path": "M2 22 22 2M7 16a1 1 0 0 0 2 0a1 1 0 0 0 -2 0zM15 8a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "arrow": {
    "name": "Arrow",
    "path": "M4 20 15 9M20 4l-2 8-6-6z",
    "text": false
  },
  "horizontal-line": {
    "name": "Horizontal Line",
    "path": "M2 12h20",
    "text": false
  },
  "horizontal-ray": {
    "name": "Horizontal Ray",
    "path": "M8 12h14M7 12a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "vertical-line": {
    "name": "Vertical Line",
    "path": "M12 2v20",
    "text": false
  },
  "cross-line": {
    "name": "Cross Line",
    "path": "M2 12h20M12 2v20M11 12a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "rectangle": {
    "name": "Rectangle",
    "path": "M3 5h18v14H3z",
    "text": false
  },
  "ellipse": {
    "name": "Ellipse",
    "path": "M12 5c5 0 9 3 9 7s-4 7-9 7-9-3-9-7 4-7 9-7z",
    "text": false
  },
  "parallel-channel": {
    "name": "Parallel Channel",
    "path": "M2 16 14 4M8 22 20 10",
    "text": false
  },
  "fib-retracement": {
    "name": "Fib Retracement",
    "path": "M3 4h18M3 9h18M3 14h18M3 19h18",
    "text": false
  },
  "fib-extension": {
    "name": "Fib Extension",
    "path": "M3 5h18M3 12h18M3 19h18M8 5v14",
    "text": false
  },
  "long-position": {
    "name": "Long Position",
    "path": "M2 14h4M6 3h15v17H6zM6 14h15M10 11l3-4 3 4z",
    "text": false
  },
  "short-position": {
    "name": "Short Position",
    "path": "M2 10h4M6 4h15v17H6zM6 10h15M10 13l3 4 3-4z",
    "text": false
  },
  "forecast": {
    "name": "Forecast",
    "path": "M3 18 9 10l4 4 8-10M13 4h8v8",
    "text": false
  },
  "measure": {
    "name": "Measure",
    "path": "M4 16h16M4 12v8M20 12v8M8 4h8M12 4v6",
    "text": false
  },
  "price-range": {
    "name": "Price Range",
    "path": "M12 4v16M7 9l5-5 5 5M7 15l5 5 5-5",
    "text": false
  },
  "date-range": {
    "name": "Date Range",
    "path": "M4 12h16M9 7l-5 5 5 5M15 7l5 5-5 5",
    "text": false
  },
  "circle": {
    "name": "Circle",
    "path": "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z",
    "text": false
  },
  "triangle": {
    "name": "Triangle",
    "path": "M12 4 21 20H3z",
    "text": false
  },
  "polyline": {
    "name": "Polyline",
    "path": "M4 19 9 7l5 9 6-11M2 19a2 2 0 0 0 4 0a2 2 0 0 0 -4 0zM7 7a2 2 0 0 0 4 0a2 2 0 0 0 -4 0zM12 16a2 2 0 0 0 4 0a2 2 0 0 0 -4 0z",
    "text": false
  },
  "arc": {
    "name": "Arc",
    "path": "M3 19a12 12 0 0 1 18 0",
    "text": false
  },
  "curve": {
    "name": "Curve",
    "path": "M3 18c4-12 14-12 18 0",
    "text": false
  },
  "rotated-rectangle": {
    "name": "Rotated Rectangle",
    "path": "M2 14 10 4l12 6-8 10z",
    "text": false
  },
  "double-curve": {
    "name": "Double Curve",
    "path": "M3 18c3-9 7-9 9 0 2 9 6 9 9 0",
    "text": false
  },
  "arrow-up": {
    "name": "Arrow Up",
    "path": "M12 3v18M6 9l6-6 6 6",
    "text": false
  },
  "arrow-down": {
    "name": "Arrow Down",
    "path": "M12 3v18M6 15l6 6 6-6",
    "text": false
  },
  "highlighter": {
    "name": "Highlighter",
    "path": "M4 16 14 6l4 4-10 10H4z",
    "text": false
  },
  "brush": {
    "name": "Brush",
    "path": "M3 19c4 0 4-8 8-8s4 8 9 4",
    "text": false
  },
  "fib-channel": {
    "name": "Fib Channel",
    "path": "M2 14 14 4M4 18 16 8M6 22 18 12",
    "text": false
  },
  "fib-time-zone": {
    "name": "Fib Time Zone",
    "path": "M4 3v18M8 3v18M14 3v18M22 3v18",
    "text": false
  },
  "fib-fan": {
    "name": "Fib Fan",
    "path": "M3 20 21 4M3 20 21 10M3 20 21 16M3 20h18",
    "text": false
  },
  "gann-fan": {
    "name": "Gann Fan",
    "path": "M3 20 21 2M3 20 21 9M3 20 21 15M3 20h18",
    "text": false
  },
  "gann-box": {
    "name": "Gann Box",
    "path": "M3 3h18v18H3zM3 3l18 18M3 21 21 3",
    "text": false
  },
  "cyclic-lines": {
    "name": "Cyclic Lines",
    "path": "M4 4v16M10 4v16M16 4v16M22 4v16",
    "text": false
  },
  "time-cycles": {
    "name": "Time Cycles",
    "path": "M4 12a4 4 0 0 1 8 0 4 4 0 0 0 8 0M4 4v16",
    "text": false
  },
  "sine-line": {
    "name": "Sine Line",
    "path": "M2 12c3-9 6-9 9 0 3 9 6 9 9 0",
    "text": false
  },
  "text": {
    "name": "Text",
    "path": "M4 5h16M12 5v14M8 19h8",
    "text": true,
    "fields": [
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.align",
      "text.valign",
      "text.wrap",
      "text.wrapWidth",
      "text.background",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor",
      "space"
    ]
  },
  "path": {
    "name": "Path",
    "path": "M3 20 7 7l5 9 5-5M20 8l-6 2 4 4z",
    "text": false
  },
  "price-label": {
    "name": "Price Label",
    "path": "M3 12 8 7h13v10H8z",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic"
    ]
  },
  "callout": {
    "name": "Callout",
    "path": "M3 3h18v9H11l-6 8 1-8H3z",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic"
    ]
  },
  "flag-mark": {
    "name": "Flag Mark",
    "path": "M6 21V3M6 3h12l-3 4 3 4H6",
    "text": false
  },
  "note": {
    "name": "Note",
    "path": "M4 20 9 15M9 5h13v10H9zM4 20v-4",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "balloon": {
    "name": "Balloon",
    "path": "M3 4h18v12H9l-4 4v-4H3z",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "comment": {
    "name": "Comment",
    "path": "M3 5h18v10H3zM6 15v4l4-4",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "signpost": {
    "name": "Signpost",
    "path": "M12 21V9M5 3h14v6H5z",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "price-note": {
    "name": "Price Note",
    "path": "M2 12h5M7 6h15v12H7zM10 12h9",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "table": {
    "name": "Table",
    "path": "M3 5h18v14H3zM3 10h18M9 10v9M15 10v9",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor",
      "space"
    ]
  },
  "arrow-left": {
    "name": "Arrow Left",
    "path": "M3 12h18M9 6l-6 6 6 6",
    "text": false
  },
  "arrow-right": {
    "name": "Arrow Right",
    "path": "M3 12h18M15 6l6 6-6 6",
    "text": false
  },
  "disjoint-channel": {
    "name": "Disjoint Channel",
    "path": "M2 16 14 6M8 22 22 14",
    "text": false
  },
  "flat-top-bottom": {
    "name": "Flat Top/Bottom",
    "path": "M3 6h18M3 20 21 12M3 6v14",
    "text": false
  },
  "regression-channel": {
    "name": "Regression Channel",
    "path": "M3 18 19 6M5 21 21 9M3 12 17 2M10 16h4",
    "text": false
  },
  "pitchfork": {
    "name": "Pitchfork",
    "path": "M5 2v8h14V2M12 2v19M11 21a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "schiff-pitchfork": {
    "name": "Schiff Pitchfork",
    "path": "M5 2v8h14V2M12 2v12h7M18 14a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "modified-schiff-pitchfork": {
    "name": "Modified Schiff Pitchfork",
    "path": "M5 2v8h14V2M12 2v13M5 10l14 10M18 20a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "inside-pitchfork": {
    "name": "Inside Pitchfork",
    "path": "M5 2v8h14V2M12 2v8M5 10l7 10 7-10M11 20a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "info-line": {
    "name": "Info Line",
    "path": "M6 18 18 6M3 3h8v5H3zM5 18a1 1 0 0 0 2 0a1 1 0 0 0 -2 0zM17 6a1 1 0 0 0 2 0a1 1 0 0 0 -2 0z",
    "text": false
  },
  "trend-angle": {
    "name": "Trend Angle",
    "path": "M4 20 18 8M4 20h12M8 20a8 8 0 0 0 2-5",
    "text": false
  },
  "fib-extension-two-point": {
    "name": "Fib Extension (Two Point)",
    "path": "M3 4h18M3 10h18M3 16h18M3 21h18M6 4v12",
    "text": false
  },
  "fib-speed-resistance-fan": {
    "name": "Fib Speed Resistance Fan",
    "path": "M3 3h18v18M3 21 21 3M21 12 3 21 12 3",
    "text": false
  },
  "icon-stamp": {
    "name": "Icon Stamp",
    "path": "M12 3l3 6 6 3-6 3-3 6-3-6-6-3 6-3z",
    "text": false
  },
  "trend-fib-time": {
    "name": "Trend Fib Time",
    "path": "M3 20 8 8 12 15M12 3v18M16 3v18M22 3v18",
    "text": false
  },
  "fib-circles": {
    "name": "Fib Circles",
    "path": "M9 12a3 3 0 0 0 6 0a3 3 0 0 0 -6 0zM6 12a6 6 0 0 0 12 0a6 6 0 0 0 -12 0zM3 12a9 9 0 0 0 18 0a9 9 0 0 0 -18 0z",
    "text": false
  },
  "fib-speed-resistance-arcs": {
    "name": "Fib Speed Resistance Arcs",
    "path": "M10 14 22 2M2 6a8 8 0 0 1 16 16M6 10a4 4 0 0 1 8 8",
    "text": false
  },
  "fib-wedge": {
    "name": "Fib Wedge",
    "path": "M20 18H5l9-12M10 18A5 5 0 0 0 8 14M15 18A10 10 0 0 0 11 10M20 18A15 15 0 0 0 14 6",
    "text": false
  },
  "fib-spiral": {
    "name": "Fib Spiral",
    "path": "M8 10A2 2 0 0 0 10 8 3 3 0 0 0 7 5 5 5 0 0 0 2 10 8 8 0 0 0 10 18 13 13 0 0 0 22 10",
    "text": false
  },
  "gann-square": {
    "name": "Gann Square",
    "path": "M3 3h18v18H3zM9 3v18M15 3v18M3 9h18M3 15h18M3 21 21 3",
    "text": false
  },
  "dedekind-tessellation": {
    "name": "Dedekind Tessellation",
    "path": "M3 3h18v18H3zM3 3A18 18 0 0 1 21 21M21 3A18 18 0 0 0 3 21M3 21a6 6 0 0 1 12 0M9 21a6 6 0 0 1 12 0M12 3 12 21",
    "text": false
  },
  "sonic": {
    "name": "Sonic",
    "path": "M3 12a9 9 0 0 1 18 0M6 12a6 6 0 0 1 12 0M9 12a3 3 0 0 1 6 0M3 12h18",
    "text": false
  },
  "supersonic": {
    "name": "Supersonic",
    "path": "M22 3 2 12l20 9M5 12a2 2 0 0 0 4 0a2 2 0 0 0 -4 0zM8 12a4 4 0 0 0 8 0a4 4 0 0 0 -8 0z",
    "text": false
  },
  "golden-sonic": {
    "name": "Golden Sonic",
    "path": "M3 12a9 9 0 0 1 18 0M7 12a5 5 0 0 1 10 0M10 12a2 2 0 0 1 4 0M3 16h18M12 16v5",
    "text": false
  },
  "golden-supersonic": {
    "name": "Golden Supersonic",
    "path": "M22 5 2 12l20 7M5 12a2 2 0 0 0 4 0a2 2 0 0 0 -4 0zM8 12a3 3 0 0 0 6 0a3 3 0 0 0 -6 0zM12 12a5 5 0 0 0 10 0a5 5 0 0 0 -10 0z",
    "text": false
  },
  "xabcd-pattern": {
    "name": "XABCD Pattern",
    "path": "M3 19 7 4 12 16 16 8 21 20M3 19 12 16 21 20M7 4 16 8",
    "text": false
  },
  "abcd-pattern": {
    "name": "ABCD Pattern",
    "path": "M3 18 9 4 15 15 21 3M3 18 15 15M9 4 21 3",
    "text": false
  },
  "elliott-impulse": {
    "name": "Elliott Impulse",
    "path": "M2 21 6 12 9 17 13 5 17 11 22 2",
    "text": false
  },
  "elliott-correction": {
    "name": "Elliott Correction",
    "path": "M3 4 9 18 15 8 21 21M3 4h4M17 21h4",
    "text": false
  },
  "head-shoulders": {
    "name": "Head and Shoulders",
    "path": "M2 20 5 10 8 17 12 3 16 17 19 10 22 20M3 17h18",
    "text": false
  },
  "gartley": {
    "name": "Gartley",
    "path": "M2 21 7 3 12 14 17 7 22 17M2 21 12 14 22 17",
    "text": false
  },
  "bat": {
    "name": "Bat",
    "path": "M2 21 7 3 12 11 17 5 22 19M2 21 12 11 22 19",
    "text": false
  },
  "butterfly": {
    "name": "Butterfly",
    "path": "M2 16 7 3 12 13 17 6 22 21M2 16 12 13 22 21",
    "text": false
  },
  "crab": {
    "name": "Crab",
    "path": "M2 14 7 2 12 9 17 4 22 21M2 14 12 9 22 21",
    "text": false
  },
  "shark": {
    "name": "Shark",
    "path": "M2 22 7 5 12 13 17 2 22 22M2 22 12 13 22 22",
    "text": false
  },
  "cypher": {
    "name": "Cypher",
    "path": "M2 21 7 7 12 14 17 2 22 17M2 21 12 14 22 17",
    "text": false
  },
  "anchored-vwap": {
    "name": "Anchored VWAP",
    "path": "M4 4v16M4 15 8 12 12 14 16 8 20 6M2 4h4",
    "text": false
  },
  "fixed-range-volume-profile": {
    "name": "Fixed Range Volume Profile",
    "path": "M4 3v18M4 5h8v3H4M4 10h16v3H4M4 15h12v3H4",
    "text": false
  }
}

export const DRAW_TOOL_ICON_ATTRS = {
  "viewBox": "0 0 24 24",
  "fill": "none",
  "stroke": "currentColor",
  "strokeWidth": 2,
  "strokeLinecap": "round",
  "strokeLinejoin": "round"
} as const
