// Generated by frontend/scripts/generate-drawing-tools.mjs from the pinned package.
// Metadata keeps the menu independent of the lazily loaded drawing renderer.
export const DRAW_TOOL_METADATA: Readonly<Record<string, { name: string; path: string; text: boolean; fields?: readonly string[] }>> = {
  "trend-line": {
    "name": "Trend Line",
    "path": "M4 20 20 4",
    "text": false
  },
  "ray": {
    "name": "Ray",
    "path": "M4 20 20 4M2 18 6 22",
    "text": false
  },
  "extended-line": {
    "name": "Extended Line",
    "path": "M2 22 22 2",
    "text": false
  },
  "arrow": {
    "name": "Arrow",
    "path": "M4 20 18 6M18 6h-6M18 6v6",
    "text": false
  },
  "horizontal-line": {
    "name": "Horizontal Line",
    "path": "M2 12h20",
    "text": false
  },
  "horizontal-ray": {
    "name": "Horizontal Ray",
    "path": "M6 12H22M4 10V14",
    "text": false
  },
  "vertical-line": {
    "name": "Vertical Line",
    "path": "M12 2v20",
    "text": false
  },
  "cross-line": {
    "name": "Cross Line",
    "path": "M2 12h20M12 2v20",
    "text": false
  },
  "rectangle": {
    "name": "Rectangle",
    "path": "M3 5h18v14H3z",
    "text": false
  },
  "ellipse": {
    "name": "Ellipse",
    "path": "M12 5c5 0 9 3 9 7s-4 7-9 7-9-3-9-7 4-7 9-7z",
    "text": false
  },
  "parallel-channel": {
    "name": "Parallel Channel",
    "path": "M2 16 14 4M8 22 20 10",
    "text": false
  },
  "fib-retracement": {
    "name": "Fib Retracement",
    "path": "M3 4h18M3 9h18M3 14h18M3 19h18",
    "text": false
  },
  "fib-extension": {
    "name": "Fib Extension",
    "path": "M3 5h18M3 12h18M3 19h18M8 5v14",
    "text": false
  },
  "long-position": {
    "name": "Long Position",
    "path": "M3 15h18v5H3zM3 5h18v5H3zM12 10v5",
    "text": false
  },
  "short-position": {
    "name": "Short Position",
    "path": "M3 5h18v5H3zM3 15h18v5H3zM12 10v5",
    "text": false
  },
  "forecast": {
    "name": "Forecast",
    "path": "M3 18 9 10l4 4 8-10M13 4h8v8",
    "text": false
  },
  "measure": {
    "name": "Measure",
    "path": "M4 16h16M4 12v8M20 12v8M8 4h8M12 4v6",
    "text": false
  },
  "price-range": {
    "name": "Price Range",
    "path": "M12 4v16M8 8l4-4 4 4M8 16l4 4 4-4",
    "text": false
  },
  "date-range": {
    "name": "Date Range",
    "path": "M4 12h16M8 8l-4 4 4 4M16 8l4 4-4 4",
    "text": false
  },
  "circle": {
    "name": "Circle",
    "path": "M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z",
    "text": false
  },
  "triangle": {
    "name": "Triangle",
    "path": "M12 4 21 20H3z",
    "text": false
  },
  "polyline": {
    "name": "Polyline",
    "path": "M2 18 8 8l4 6 4-10 4 4",
    "text": false
  },
  "arc": {
    "name": "Arc",
    "path": "M3 19a12 12 0 0 1 18 0",
    "text": false
  },
  "curve": {
    "name": "Curve",
    "path": "M3 18c4-12 14-12 18 0",
    "text": false
  },
  "rotated-rectangle": {
    "name": "Rotated Rectangle",
    "path": "M2 14 10 4l12 6-8 10z",
    "text": false
  },
  "double-curve": {
    "name": "Double Curve",
    "path": "M3 18c3-9 7-9 9 0 2 9 6 9 9 0",
    "text": false
  },
  "arrow-up": {
    "name": "Arrow Up",
    "path": "M12 3v18M6 9l6-6 6 6",
    "text": false
  },
  "arrow-down": {
    "name": "Arrow Down",
    "path": "M12 3v18M6 15l6 6 6-6",
    "text": false
  },
  "highlighter": {
    "name": "Highlighter",
    "path": "M4 16 14 6l4 4-10 10H4z",
    "text": false
  },
  "brush": {
    "name": "Brush",
    "path": "M3 19c4 0 4-8 8-8s4 8 9 4",
    "text": false
  },
  "fib-channel": {
    "name": "Fib Channel",
    "path": "M2 14 14 4M4 18 16 8M6 22 18 12",
    "text": false
  },
  "fib-time-zone": {
    "name": "Fib Time Zone",
    "path": "M4 3v18M8 3v18M14 3v18M22 3v18",
    "text": false
  },
  "fib-fan": {
    "name": "Fib Fan",
    "path": "M3 20 21 4M3 20 21 10M3 20 21 16M3 20h18",
    "text": false
  },
  "gann-fan": {
    "name": "Gann Fan",
    "path": "M3 20 21 2M3 20 21 9M3 20 21 15M3 20h18",
    "text": false
  },
  "gann-box": {
    "name": "Gann Box",
    "path": "M3 3h18v18H3zM3 3l18 18M3 21 21 3",
    "text": false
  },
  "cyclic-lines": {
    "name": "Cyclic Lines",
    "path": "M4 4v16M10 4v16M16 4v16M22 4v16",
    "text": false
  },
  "time-cycles": {
    "name": "Time Cycles",
    "path": "M4 12a4 4 0 0 1 8 0 4 4 0 0 0 8 0M4 4v16",
    "text": false
  },
  "sine-line": {
    "name": "Sine Line",
    "path": "M2 12c3-9 6-9 9 0 3 9 6 9 9 0",
    "text": false
  },
  "text": {
    "name": "Text",
    "path": "M4 5h16M12 5v14M8 19h8",
    "text": true,
    "fields": [
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.align",
      "text.valign",
      "text.wrap",
      "text.wrapWidth",
      "text.background",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "path": {
    "name": "Path",
    "path": "M2 18 8 8l4 6 4-10",
    "text": false
  },
  "price-label": {
    "name": "Price Label",
    "path": "M3 12 8 7h13v10H8z",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic"
    ]
  },
  "callout": {
    "name": "Callout",
    "path": "M3 4h18v11H3zM8 15l-2 5 6-5",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic"
    ]
  },
  "flag-mark": {
    "name": "Flag Mark",
    "path": "M6 21V3M6 3h12l-3 4 3 4H6",
    "text": false
  },
  "note": {
    "name": "Note",
    "path": "M4 20 9 15M9 5h13v10H9zM4 20v-4",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "balloon": {
    "name": "Balloon",
    "path": "M3 4h18v12H9l-4 4v-4H3z",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "comment": {
    "name": "Comment",
    "path": "M3 5h18v10H3zM6 15v4l4-4",
    "text": true,
    "fields": [
      "style.color",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "signpost": {
    "name": "Signpost",
    "path": "M12 21V9M5 3h14v6H5z",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "price-note": {
    "name": "Price Note",
    "path": "M2 12h5M7 6h15v12H7zM10 12h9",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "table": {
    "name": "Table",
    "path": "M3 5h18v14H3zM3 10h18M9 10v9M15 10v9",
    "text": true,
    "fields": [
      "style.color",
      "style.lineWidth",
      "text.value",
      "text.color",
      "text.fontSize",
      "text.fontFamily",
      "text.bold",
      "text.italic",
      "text.backgroundColor",
      "text.backgroundOpacity",
      "text.border",
      "text.borderColor"
    ]
  },
  "arrow-left": {
    "name": "Arrow Left",
    "path": "M3 12h18M9 6l-6 6 6 6",
    "text": false
  },
  "arrow-right": {
    "name": "Arrow Right",
    "path": "M3 12h18M15 6l6 6-6 6",
    "text": false
  },
  "disjoint-channel": {
    "name": "Disjoint Channel",
    "path": "M2 16 14 6M8 22 22 14",
    "text": false
  },
  "flat-top-bottom": {
    "name": "Flat Top/Bottom",
    "path": "M3 6h18M3 20 21 12M3 6v14",
    "text": false
  },
  "regression-channel": {
    "name": "Regression Channel",
    "path": "M3 18 19 6M5 21 21 9M3 12 17 2M10 16h4",
    "text": false
  },
  "pitchfork": {
    "name": "Pitchfork",
    "path": "M4 21 16 9M4 9 16 21M10 15 22 3M4 9 10 3M16 21l6-6",
    "text": false
  },
  "schiff-pitchfork": {
    "name": "Schiff Pitchfork",
    "path": "M4 19 18 5M4 11 12 19M8 15 20 3M4 11l6-6M12 19l8-8",
    "text": false
  },
  "modified-schiff-pitchfork": {
    "name": "Modified Schiff Pitchfork",
    "path": "M4 20 20 4M4 12 12 20M8 16 20 4M4 12l8-8M12 20l8-8",
    "text": false
  },
  "inside-pitchfork": {
    "name": "Inside Pitchfork",
    "path": "M4 20 20 4M6 10 14 18M6 10l6-6M14 18l6-6",
    "text": false
  },
  "info-line": {
    "name": "Info Line",
    "path": "M4 20 20 4M8 8h8",
    "text": false
  },
  "trend-angle": {
    "name": "Trend Angle",
    "path": "M4 20 18 8M4 20h12M8 20a8 8 0 0 0 2-5",
    "text": false
  },
  "fib-extension-two-point": {
    "name": "Fib Extension (Two Point)",
    "path": "M3 4h18M3 10h18M3 16h18M3 21h18M6 4v12",
    "text": false
  },
  "fib-speed-resistance-fan": {
    "name": "Fib Speed Resistance Fan",
    "path": "M3 21V3M3 21h18M3 21 21 3M3 21 12 3M3 21 21 12",
    "text": false
  },
  "icon-stamp": {
    "name": "Icon Stamp",
    "path": "M12 3l3 6 6 3-6 3-3 6-3-6-6-3 6-3z",
    "text": false
  },
  "trend-fib-time": {
    "name": "Trend Fib Time",
    "path": "M3 20 8 8 12 15M12 3v18M16 3v18M22 3v18",
    "text": false
  },
  "fib-circles": {
    "name": "Fib Circles",
    "path": "M12 20A5 5 0 0 1 12 10M12 20A9 9 0 0 1 12 2M10 20h4",
    "text": false
  },
  "fib-speed-resistance-arcs": {
    "name": "Fib Speed Resistance Arcs",
    "path": "M3 21a6 6 0 0 0 6-6M3 21a12 12 0 0 0 12-12M3 21a18 18 0 0 0 18-18M3 21 21 3",
    "text": false
  },
  "fib-wedge": {
    "name": "Fib Wedge",
    "path": "M3 20 21 4M3 20 21 12M3 20a12 12 0 0 0 10-6",
    "text": false
  },
  "fib-spiral": {
    "name": "Fib Spiral",
    "path": "M12 13A3 3 0 1 1 15 10A7 7 0 1 1 8 3A9 9 0 1 1 21 12",
    "text": false
  },
  "gann-square": {
    "name": "Gann Square",
    "path": "M3 3h18v18H3zM9 3v18M15 3v18M3 9h18M3 15h18M3 21 21 3",
    "text": false
  },
  "dedekind-tessellation": {
    "name": "Dedekind Tessellation",
    "path": "M3 21a9 9 0 0 1 18 0M3 21a4 4 0 0 1 8 0M13 21a4 4 0 0 1 8 0M12 3v18",
    "text": false
  },
  "sonic": {
    "name": "Sonic",
    "path": "M3 12a9 9 0 0 1 18 0M6 12a6 6 0 0 1 12 0M9 12a3 3 0 0 1 6 0M3 12h18",
    "text": false
  },
  "supersonic": {
    "name": "Supersonic",
    "path": "M3 12 21 3M3 12l18 9M7 12a5 5 0 0 1 10 0M10 12a3 3 0 0 1 6 0",
    "text": false
  },
  "golden-sonic": {
    "name": "Golden Sonic",
    "path": "M3 12a9 9 0 0 1 18 0M7 12a5 5 0 0 1 10 0M10 12a2 2 0 0 1 4 0M3 16h18M12 16v5",
    "text": false
  },
  "golden-supersonic": {
    "name": "Golden Supersonic",
    "path": "M3 12 21 3M3 12l18 9M6 12a6 6 0 0 1 12 0M10 12a2 2 0 0 1 4 0M18 11v2",
    "text": false
  },
  "xabcd-pattern": {
    "name": "XABCD Pattern",
    "path": "M3 19 7 4 12 16 16 8 21 20M3 19 12 16 21 20M7 4 16 8",
    "text": false
  },
  "abcd-pattern": {
    "name": "ABCD Pattern",
    "path": "M3 18 9 4 15 15 21 3M3 18 15 15M9 4 21 3",
    "text": false
  },
  "elliott-impulse": {
    "name": "Elliott Impulse",
    "path": "M2 21 6 12 9 17 13 5 17 11 22 2",
    "text": false
  },
  "elliott-correction": {
    "name": "Elliott Correction",
    "path": "M3 4 9 18 15 8 21 21M3 4h4M17 21h4",
    "text": false
  },
  "head-shoulders": {
    "name": "Head and Shoulders",
    "path": "M2 20 5 10 8 17 12 3 16 17 19 10 22 20M3 17h18",
    "text": false
  },
  "gartley": {
    "name": "Gartley",
    "path": "M3 20 7 3 12 13 16 7 21 17M3 20 12 13 21 17",
    "text": false
  },
  "bat": {
    "name": "Bat",
    "path": "M3 21 7 3 12 11 16 6 21 19M7 3 16 6M3 21 21 19",
    "text": false
  },
  "butterfly": {
    "name": "Butterfly",
    "path": "M3 16 7 3 12 14 16 7 21 21M3 16 12 14 21 21",
    "text": false
  },
  "crab": {
    "name": "Crab",
    "path": "M3 12 7 3 12 10 16 5 21 22M3 12 12 10 21 22",
    "text": false
  },
  "shark": {
    "name": "Shark",
    "path": "M3 17 7 10 12 20 16 3 21 18M3 17 21 18M7 10 16 3",
    "text": false
  },
  "cypher": {
    "name": "Cypher",
    "path": "M3 20 7 9 12 16 16 3 21 18M3 20 12 16M7 9 16 3",
    "text": false
  }
}

export const DRAW_TOOL_ICON_ATTRS = {
  "viewBox": "0 0 24 24",
  "fill": "none",
  "stroke": "currentColor",
  "strokeWidth": 2,
  "strokeLinecap": "round",
  "strokeLinejoin": "round"
} as const
